snabbco/snabb

src/apps/packet_filter/README.md
src/apps/packet_filter/README.md.src
src/apps/packet_filter/conntrack.lua
src/apps/packet_filter/packet_filter.lua

This is a much better API for stateful filters.  In short: there are named "connection tables".  If a filter rule includes a `state_track = "name"` entry, any packet that passes that specific rule is tracked in that table.  A `state_check = "name"` entry adds to the rule the condition that this packet belongs to an existing connection.  Either of these lines can also appear 'naked', outside of any rule, which adds a state checking and/or tracking before any filter test.
The code seems clean and readable to me, but still need some real tests; the current `selftest()` just exercises the different options to show the generated code and track tables.

stateful packet_filter

---

src/apps/intel/intel10g.lua
src/apps/intel/intel_app.lua
src/core/app.lua
src/lib/index_set.lua
src/lib/nfv/selftest.sh
src/test_fixtures/nfvconfig/test_functions/other_vlan.ports

It works. :+1:
This branch includes commits by Javier which fix bugs in the Intel driver related to on-line reconfiguration.

Reuse VMs and snabbnfv-traffic instance in lib/nfv/selftest.sh

---

src/designs/neutron/snabbnfv-fuzz
src/lib/nfv/fuzz.lua
src/lib/nfv/selftest.sh
src/test_fixtures/nfvconfig/fuzz/filter2-tunnel-txrate10-ports.spec

This adds a fuzzing function to the NFV selftest. The fuzzer generates semi-random NFV configurations that allow a successful `iperf` run between two VMs to test the configuration. The fuzzer's output can be controlled using a "spec" file which might look like this:
```
return { ingress_filter = 2, -- generate two random ingress filter rules (in addition to rules for iperf)
egress_filter = 2, -- generate two random egress filter rules (in addition to rules for iperf)
tunnel = true, -- do generate a tunnel config
tx_police_gbps = 10 } -- do generate random value 1...10 (rx_police_gbps is also recognized)
```
If a key is omitted or `nil` then the config part in question is omitted.

NFV config fuzz

---

src/lib/ipc/shmem/counter.lua
src/lib/ipc/shmem/mib.lua
src/lib/ipc/shmem/shmem.c
src/lib/ipc/shmem/shmem.h
src/lib/ipc/shmem/shmem.lua

I'd like to pick up on a suggestion for sharing counters with other processes by Luke in the thread 
https://groups.google.com/d/msg/snabb-devel/-Ka_gPfd88k/tL0wTqxcizcJ
I commented back then that I was thinking about something like that to implement an interface to a SNMP agent. I have done this by generalzing Luke's code from https://github.com/lukego/snabbswitch/blob/counter/src/core/counter.lua
I think that this (or something similar) might be worth adding to the Snabb core.
The "mib" subclass supports all basic SMIv2 types.  And, yes, I have working code for my VPN app and a SNMP sub-agent (written in Perl) that allows me to monitor my system with our standard monitoring system via SNMP (based on Nagios). I'm really pleased with that :)
I have also implemented Luke's "counter" module …

IPC method using file-backed shared memory

---

src/apps/vhost/vhost.lua
src/apps/vhost/vhost_apps.lua
src/core/app.lua
src/core/memory.c
src/core/memory.h
src/core/memory.lua
src/core/packet.lua
src/lib/nfv/selftest.sh
src/lib/virtio/net_device.lua
src/lib/virtio/virtq.lua

In this branch we remove the zero-copy functionality for virtio and we simplify the packet structure (single buffer only).
NOTE: Requires LuaJIT update to the latest 2.1 version
Measured performance:
On 0000:82:00.0 got 4.134
Rate(Mpps):     4.134
Measured performance 2xPCI on different NUMA nodes:
On 0000:05:00.0 got 4.075
On 0000:82:00.0 got 4.039
Rate(Mpps):     8.114
Output of make test:
TEST      lib.hash.murmur
TEST      lib.tlb
TEST      lib.nfv.config
TEST      lib.protocol.ipv6
TEST      lib.protocol.ipv4
TEST      lib.bloom_filter
TEST      lib.hardware.pci
TEST      core.lib
TEST      core.memory
TEST      core.link
TEST      core.timer
TEST      core.app
SKIPPED   testlog/core.app
TEST      apps.packet_filter.packet_filter
TEST      apps.packet_filter.packet_filter_benchmark …

Straightline

---

src/apps/intel/intel10g.lua
src/apps/intel/intel_app.lua
src/lib/hardware/pci.c
src/lib/hardware/pci.h
src/lib/hardware/pci.lua

- unmaps PCI resource on device close
- deallocates buffers on (vf) app close
- don't (always) force sfi mode, autonegotiation handles this.
- if the link doesn't come up, reset the chip and try once more.
The last point in particular made _all_ cards on both davos and grindelwald pass all tests.  I couldn't test on chur because it's all tied up in some long-term process.
No more "flaky hardware" excuses!

Intel10G: better initialization / closing

---

src/core/main.lua
src/designs/neutron/snabbnfv-bench

src/designs/neutron/snabbnfv-bench has support for gettting a profile session via NFV_PROF env variable. This patch adds support for writing the result of the profile to a file (NFV_PROF_FILE) and implements support for dumps (NFV_DUMP, NFV_DUMP_FILE).

Add support for jit.dump and jit.profile to a file.

---

src/lib/ipc/shmem/counter.lua
src/lib/ipc/shmem/mib.lua
src/lib/ipc/shmem/shmem.lua

As mentioned in the discussion of PR#348, the original version was a bit half-baked concerning access to the shared memory segment between re-mappings induced by register(). My suggestion in this PR is to hand out a table with pre-computed pointers after all objects have been registered to avoid the pointer-arithemtic in the get() and set() methods.
This is implemented by the new dictionary() method, which also returns tables to translate object names into "handles" (integer index into the main object pointer table). The register() method now returns the object's handle instead of the rather useless pointer.
The "procedural interface" of the counter module needed some fixing as well (is it useful at all?).

Improve efficiency of lib/ipc/shmem mechanism

---

src/designs/neutron/neutron-sync-agent
src/designs/neutron/neutron-sync-master

Uses `git commit --amend`, `git reflog expire` and `git prune` to operate sync master and agent with constant disk space usage.
Based on this test: https://gist.github.com/eugeneia/babaa842e6e34fcf5fc1
Note: I didn't try to prune periodically (instead of after each commit/pull) because I assume that pruning a single-commit-repo will always be a cheap operation.

[neutron-sync] Use constant disk space for neutron-sync-master/neutron-sync-agent

---

src/apps/intel/intel10g.lua
src/apps/intel/intel_app.lua

1. The `manyreconf()` function does two different tests: "VF-only": a hundred reconfiguration cycles for the same apps, the hardware is mostly set up once.  and "full PF cycle": a hundred full tear-down and reinitialization cycles.  Now the `selftest` does both.
1. The `autonegotiate_sfi()` was shown to do more harm than good when not needed, so it's now an optional part of the initialization.
1. When everything is going well, the NIC is initialized in typically 160msec, so the timeout is now 250msec, as per the Intel docs (down from 500).
1. If the NIC isn't up after 250msec, we reinitialize it, and in the vast majority of cases (well over 98%) it's done in 150-180msec.
1. In a few cases it won't come up until we do an `autonegotiate_sfi()`.  After that, it behaves normally.
1. Some …

Intel10G: extensive reconfig tests and better initalization

---

src/lib/nfv/README.md
src/lib/nfv/README.md.src
src/lib/nfv/config.lua
src/lib/nfv/selftest.sh
src/test_fixtures/nfvconfig/test_functions/rx_rate_limit.ports
src/test_fixtures/nfvconfig/test_functions/tx_rate_limit.ports

Rename snabbfv-traffic's rx_police_gbps to tx_police_gbps and add proper rx_police_gbps. I started a mailing list thread about my woes actually testing rate limiting but I believe solving these is not in the scope of this PR. Nevertheless this branch extends the NFV selftest with a function `test_rate_limited` that allows testing of effective rate limiting. This functions is used to test the changes for ballpark sanity.

Rename snabbfv-traffic's rx_police_gbps to tx_police_gbps and add proper rx_police_gbps

---

.gitignore
.gitmodules
Makefile

This will enable us to rewrite most of our C glue code in Lua.
ljsyscall is an extensive LuaJIT FFI interface towards the kernel:
https://github.com/justincormack/ljsyscall
The source code is added as a submodule in deps/ljsyscall.
The top-level Makefile copies required source files directly into
src/. Only the code for Linux/x86-64 is imported.
The top-level .gitignore file matches on the copied files.

Add ljsyscall to Snabb Switch [DRAFT]

---

src/lib/nfv/selftest.sh

This fixes a regression of the keep-nfv branch where a globally shared pathname (TESTCONFPATH) was erroneously introduced.

[lib/nfv/selftest.sh] Make TESTCONFPATH process specific ($$)

---

Makefile
gcc-preinclude.h
src/Makefile
src/selftest.sh

Prepare dynamic linking so that `./snabb` is compatible with all GLIBC versions >= 2.7. This enables us to release Snabb Switch as a single executable file for any modern Linux/x86_64.
Tested when built on Ubuntu 14.04. Building with newer versions of GLIBC can potentially break backwards compatibility. A `selftest.sh` script is included to detect this.
Makefile now forces GCC to always include the file `gcc-preinclude.h`. This file can contain `.symver` directives to break dependencies on new GLIBC versions.
There is currently one such directive forcing `memcpy` to bind to the GLIBC 2.2.5 symbol instead of GLIBC 2.14. (This is because GLIBC made a semi-backwards-incompatible change to `memcpy` in version 2.14.) Loosely speaking, this has the side-effect of forcing `memcpy` to act like …

Make ./snabb binary more portable

---

src/lib/nfv/selftest.sh

Perform cleanup in trap instead of invoking it manually before calling `exit`.

[lib/nfv/selftest.sh] Perform cleanup in trap.

---

src/scripts/snabb_bot/snabb_bot.sh

Instead fetch submodules before every make. This bug was responsible for build errors when the submodules changed.

[snabb_bot] Fix bug where submodules where refetched only once

---

src/apps/intel/intel10g.lua
src/core/memory.c

Initialize DMA memory to reasonable and predictable values. Reduce the risk of bugs overwriting memory.
Could be to interesting @javierguerragiraldez and @eugeneia?

Initialize DMA memory more deliberately

---

src/apps/intel/README.md
src/apps/intel/README.md.src
src/apps/intel/intel10g.lua
src/apps/intel/intel_app.lua
src/doc/genbook.sh
src/lib/hardware/README.md
src/lib/hardware/README.md.src
src/lib/hardware/pci.lua
src/lib/hardware/register.lua

1. Polishes the code at `lib/hardware` a bit and adds proper documentation.
2. Fix more or less critical bugs related to `lib.hardware.pci` usage.

lib.hardware.* improvements

---

src/program/snabbnfv/traffic/traffic.lua

The command `snabbnfv traffic` is broken without this fix.

snabbnfv traffic: Add missing 'require' that broke program

---

README.md
src/program/snabbnfv/selftest.sh
src/scripts/bench_env/common.sh
src/scripts/cperf/benchmarks/basic1-10e6
src/scripts/cperf/benchmarks/iperf-jumbo
src/scripts/cperf/cperf.sh
src/scripts/snabb_bot/tasks/test.sh

This branch adds a new `iperf-jumbo` benchmark based on the snabbnfv selftest, increases snabbnfv selftest verbosity, updates `cperf.sh check` to persist results and includes other minor improvements.

Various SnabbBot, cperf, snabbnfv selftest and bench_env updates

---

src/program/snabbnfv/neutron_sync_master/neutron_sync_master.sh

The default value for DB_NEUTRON_TABLES variable contains: "qos_policies qoses portqosmappings" which is not used anymore by the neutron2snabb program.

neutron_sync_master.sh: remove DB tables no longer used

---

.gitignore

This branch contains tiny improvements. Initially an update of `.gitignore` so that `git status` can be clean after a build.

Tiny improvements

---

src/apps/packet_filter/packet_filter.lua

Ensure that ARP is always allowed when any IPv4 rule is defined.

packet_filter: Always allow ARP with IPv4

---

src/program/snabbnfv/neutron2snabb/neutron2snabb.lua

Adds `tx_police_gbps` field to `neutron2snabb` output. Removes NOOP use of `vif_details.zone_gbps` and documents why.
Fixes #393

neutron2snabb 'tx_police_gbps'

---

Makefile

Strip away these options:
-DLUAJIT_USE_PERFTOOLS
This feature causes noise in /tmp (perf-nnnn.map files). There is a
better way to profile at trace granularity with the LuaJIT
profiler. Hopefully this will be upstream in LuaJIT but for now
available as a patch:
http://www.freelists.org/post/luajit/Profile-at-trace-granularity,1
-DLUAJIT_USE_GDBJIT
The documentation says that "enabling it always has a non-negligible
overhead -- do not use in release mode" and I don't believe that we
are using this functionality (debugging JIT traces in gdb).
-DLUAJIT_NUMMODE=3
This is less clear cut. Mike Pall has encouraged us to experiment with
settings for this variable for potential performance benefits. The
current value (3) was chosen during a micro-optimization spree many
moons ago. I am not …

Makefile: Streamline LuaJIT build options

---

src/lib/checksum.c
src/lib/checksum.h
src/lib/checksum.lua
src/lib/virtio/net_device.lua

Checks incoming packets, works for both IPv4 and IPv6, TCP and UDP.
Performance seems terrible, I guess because of all the `ntohs()` calls.  I'm sure there's some way to factor them out, probably involving a little bit-shuffling.

[csum-offload-simd] Incoming checksum verification

---

Makefile
src/core/app.lua
src/core/clib.h
src/core/lib.lua
src/core/main.lua
src/core/memory.c
src/core/memory.lua
src/core/packet.lua
src/lib/checksum.c
src/lib/checksum.h
src/lib/checksum.lua
src/lib/hardware/pci.lua
src/lib/virtio/net_device.lua
src/program/snabbnfv/README
src/program/snabbnfv/neutron_sync_agent/README
src/program/snabbnfv/neutron_sync_master/README
src/program/snabbnfv/traffic/README
src/program/snabbnfv/traffic/traffic.lua

Merge with testing of open pull requests to master:
* #389 Streamline LuaJIT build options
* #414 cksum_avx2: Use unaligned loads
* #415 Run in busy-loop (Hz = false) by default
* #416 engine: Make link status printouts prettier.
* #417 Relax requirement to run as root and `mlock()` individual pages on demand
* #418 `snabbnfv`: Improve --help usage output
* #420 `snabbnfv traffic`: Fix command-line argument parsing
* #411 checksum offload: Perform checksum validation on packets sent to Virtio-net

Integrated collection of open PRs on master

---

src/lib/checksum.c

Simplify the code by operating on unaligned data. CPUs supporting AVX2
handle unaligned access very efficiently (source: Agner Fog).
The previous version of this function used a non-SIMD checksum for any
non-aligned data at the start of the packet. (This is still done for
the non-aligned part at the end, since the AVX code still operates on
minimum 32 byte chunks.)

cksum_avx2: Switch to AVX unaligned loads

---

src/core/app.lua

This will make Snabb Switch always show 100% CPU in default settings.
Previously Snabb Switch has by default attempted to bring in a batch
of new packets once every 100us. This is too conservative on the
straightline design because we now work on smaller batches of
packets (max is now 256 and was 8192 before). So this change makes the
default behavior to busy-loop without sleeping to maximize throughput.
Going forwards we should consider a dynamic mechanism that will make a
truly idle Snabb Switch sleep. Meanwhile the default is to busy-loop
and a static configuration is possible with a setting like
'engine.Hz=10000'.

Run in busy-loop (engine.Hz = false) by default

---

src/core/app.lua

The standard link report printout is now a little prettier:
* Links are alphabetically sorted (resolves #385).
* Punctuation is improved.
* Values are printed with commas and justified.
Before:
link report
597223954 sent on Virtio_A.tx -> NIC_A.rx (loss rate: 0%))
137411842 sent on NIC_A.tx -> Virtio_A.rx (loss rate: 0%))
597223786 sent on NIC_B.tx -> Virtio_B.rx (loss rate: 0%))
137411851 sent on Virtio_B.tx -> NIC_B.rx (loss rate: 0%))
After:
link report:
17,747,602 sent on NIC_A.tx -> Virtio_A.rx (loss rate: 0%)
70,955,552 sent on NIC_B.tx -> Virtio_B.rx (loss rate: 0%)
70,955,729 sent on Virtio_A.tx -> NIC_A.rx (loss rate: 0%)
17,747,621 sent on Virtio_B.tx -> NIC_B.rx (loss rate: 0%)

engine: Make link report prettier

---

src/core/clib.h
src/core/lib.lua
src/core/main.lua
src/core/memory.c
src/core/memory.lua
src/core/packet.lua
src/lib/hardware/pci.lua

Allow Snabb Switch to run as a non-root user unless/until privileged operations are required e.g. access to hardware and DMA.
These privileged operations are deferred from startup:
* Locking memory. Previously we called `mlockall()` while loading the memory module, but now we call `mlock()` individually on the HugeTLBs we allocate for DMA.
* Allocating packets. Previously we populated the packet freelist with DMA memory while loading the packet module, but now we wait until the first packet is allocated.

Relax requirement to run as root and `mlock()` less memory

---

src/program/snabbnfv/README
src/program/snabbnfv/neutron_sync_agent/README
src/program/snabbnfv/neutron_sync_master/README
src/program/snabbnfv/traffic/README
src/program/snabbnfv/traffic/traffic.lua

Added proper usage for `neutron-sync-master` and `neutron-sync-agent`.
Created separate usage commands for `traffic`: `-h/--help` prints command
line usage, `-H/--long-help` also prints the configuration file format.

snabbnfv: Improve --help usage printouts

---

src/apps/vhost/vhost_user.lua
src/program/snabbmark/snabbmark.lua
src/program/snabbnfv/README.md
src/program/snabbnfv/README.md.src
src/program/snabbnfv/nfvconfig.lua
src/program/snabbnfv/traffic/traffic.lua

[nfvconfig] Remove obsolete notion of "zerocopy pairs" and the related `nfvconfig.apply` function.
This also fixes a bug in `vhost_user` where it tried to `close(2)` a nil value. Additionally this makes `vhost_user:close` set `self.socket` to nil instead of -1 in order to avoid possible bugs when using `assert`.

[nfvconfig] Remove obsolete notion of "zerocopy pairs"

---

src/program/snabbnfv/neutron2snabb/neutron2snabb.lua

profile:bindings is not stored in the ml2_port_bindigs table
after the actual binding happens (i.e. the vm boots).
mechanism_snabb will store the value in the vif_details for persistence.

neutron2snabb: get profile:bindings from vif_details

---

src/apps/intel/intel10g.lua

This is basically the same as PR #362, except that the code is now disabled by default.  It can be enabled by
`require("apps.intel.intel10g").enable_snmp = true`
We didn't reach consensus about how to represent interfaces and intra-app links in a generic fashion, but I need something that works right now. I hope this code is acceptable at least as an interim solution.

Rudimentary support of the ifTable MIB for intel10g

---

src/core/app.lua

The "action" table is allocated each time the function is called,
which creates a fair amount of garbage, even if the restart mechanism
isn't actually used, which is the default.
This commit includes a bypass of the function if use_restart is false.
The dead-app detection code probably contains more of this kind of
garbage, e.g. in the apply_config_action() function.

Bypass core.apps.restart_dead_apps() if restart mechanism is disabled

---

src/lib/protocol/ipv6.lua
src/lib/protocol/keyed_ipv6_tunnel.lua

This is the version of the keyed-ipv6-tunnel header that I've been using for a long time. I verified that it inter-operates with the implementation on the Cisco ASR9k.

Add keyed IPv6 tunnel protocol to the lib.protocol framework

---

src/core/app.lua
src/core/lib.lua
src/core/packet.lua
src/program/snabbnfv/nfvconfig.lua
src/program/snabbnfv/traffic/README
src/program/snabbnfv/traffic/traffic.lua

"Frees per second" (fps), literally the number of calls to
packet.free() per second, is introduced as a new basic metric for
measuring work done by a Snabb Switch process.
engine.Hz = false now uses a dynamic mechanism to decide how long to
sleep for depending on how busy/idle the process is, as observed from
fps. This is now the default setting and should be suitable for normal
usage.
Load on the process can be printed by calling
engine.report_load(). The load report looks like this:
load: time: 1.00s  fps: 2,025,221   fpb: 304  bpp: 1280 sleep: 0   us
and the metrics mean:
time - period of time that the metrics were collected over
fps  - frees per second
fpb  - frees per breath
bpp  - bytes per packet (average packet size)

core: Count "frees per second" (fps) and do dynamic idling

---

.gitmodules

The upstream luajit.org git repository has automatic usage quotas the
we were exceeding them from the Snabb Lab's IP address. (Source:
private correspondence with Mike Pall.)

deps/luajit: Use github mirror of LuaJIT

---

src/program/packetblaster/packetblaster.lua

Fixes a regression introduced by the solarflare branch:
```
> @@ -54,9 +54,12 @@ function path(pcidev) return
"/sys/bus/pci/devices/"..pcidev end
>  -- Return the name of the Lua module that implements support for this
device.
>  function which_driver (vendor, device)
>     if vendor == '0x8086' then
> -      if device == '0x10fb' then return 'apps.intel.intel10g' end --
Intel 82599
> -      if device == '0x10d3' then return 'apps.intel.intel' end    --
Intel 82574L
> -      if device == '0x105e' then return 'apps.intel.intel' end    --
Intel 82571
> +      if device == '0x10fb' then return 'apps.intel.intel_app' end --
Intel 82599
```
Thanks to @alexandergall for finding this.

[packetblaster] Update `is_device_suitable' for solarflare changes

---

src/apps/packet_filter/conntrack.lua
src/apps/packet_filter/packet_filter.lua

This patch adds a `counts` table to keep track of the number of entries in the `conntracks` tables.  When a track is over an arbitrary limit (2000 entries by default), the `track()` function won't do anything (not even analyse the packet).  This not only avoids extremely big (and unpredictably slow) tables, but also makes the 'tables full' state less susceptible to (intentional?) performance drops.
This limit doesn't affect the `check()` function, so a firewall won't drop existing streams, just won't keep track of new ones.

[packet_filter] limit the number of streams tracked by stateful filters

---

src/apps/vhost/vhost_user.c
src/apps/vhost/vhost_user.lua
src/lib/virtio/net_device.lua
src/lib/virtio/virtq.lua

I have been torture-testing our vhost-user implementation under extreme conditions. This works very well now. This branch contains the fixes that I made along the way.
* Topology: `UbuntuVM1 - snabb1 - 10G - snabb2 - UbuntuVM2`
* Continuous traffic for hours (parallel iperf / ping flood).
* Continuous restarts of `snabb2` process (every ~10s).
* Continuous reboots of `VM2`.
I also made one related [change](https://github.com/SnabbCo/qemu/commit/d57042c73a6db5b2c4be74770e91f0a64086bdfd) to the QEMU side of vhost-user to protect guest memory from vhost DMA during reboots.

Virtio maint

---

src/core/lib.c

Looks like the argument passed to get_time is not being used, this diff fixes it.

in get_time() make actual use of the argument when calling clock_gettime

---

src/lib/ipc/shmem/counter.lua
src/lib/ipc/shmem/mib.lua
src/lib/ipc/shmem/shmem.c
src/lib/ipc/shmem/shmem.h
src/lib/ipc/shmem/shmem.lua

The new method allows a Snabb process to attach to an existing memory
segment as a "slave".  Only a single process is allowed to be the
"master" of a segment.  The master creates a segment via the new()
constructor, while a slave attaches to it with the attach()
constructor.  Both, master and slave have to register() the proper
data types for every object in the segment (unless the segment
contains only objects of a single, well-known type).
Currently, it is assumed that the master has finished registering objects before the first slave attaches to the segment. A slave cannot discover when a master adds more objects.
Ideas for the future: add an option to create a new segment only when the backing-files do not yet exist, otherwise perform an attach(). This could be used to simplify the …

Add attach() method to the shmem IPC mechanism

---

src/program/snabbnfv/traffic/README
src/program/snabbnfv/traffic/traffic.lua

The debug report calls engine.app_report() to report on the internal state of the apps in the network. This notably includes a register dump from the NIC.
The debug report for a simple configuration currently looks like this:
```
apps report:
A_NIC
report on intel device  0000:01:00.0
GORCL[00004088]:15c4f40c (     365,227,668) Good Octets Received Count Low
GOTCH[00004094]:00000002 (               2) Good Octets Transmitted Count High
GOTCL[00004090]:7b7299c4 (   2,071,101,684) Good Octets Transmitted Count Low
GPRC[00004074]:0027cc30 (       2,608,176) Good Packets Received Count
GPTC[00004080]:006671c1 (       6,713,789) Good Packets Transmitted Count
MLFC[00004034]:00000002 (               2) MAC Local Fault Count
MPTC[000040f0]:00000002 (               2) Multicast Packets …
```

snabbnfv traffic: Add -D/--debug-report-interval argument

---

src/program/snabbnfv/neutron_sync_master/README
src/program/snabbnfv/neutron_sync_master/neutron_sync_master.lua

The Neutron QoS feature is not used by recent Snabb NFV versions.
(The QoS API has not been merged into upstream Neutron after two years and so we don't want to depend on it.)

neutron_sync_master: Remove Neutron QoS from default tables

---

src/core/app.lua

engine.now() could return false if an app asked for the time before the breathe loop has run. This could happen when an app accesses engine.now during initialization. This indeed does happen if the initial app network uses a stateful PcapFilter.

Fix problem where engine.now() could return false

---

src/Makefile
src/arch/avx2.c
src/arch/sse2.c
src/lib/checksum.c
src/lib/checksum_lib.h

The Makefile treats these files specially: avx2.c compiles with -mavx2 and sse2.c with -msse2. This solves two problems.
First problem: The SSE2 code was actually compiling with AVX instructions because of '-mavx2'. This would cause a crash on hardware that does not support AVX or AVX2 such as an Atom CPU. (We missed this testing on the Sandy Bridge lab servers because they do support AVX even though they do not support AVX2.) Caught by Justin Cormack: https://groups.google.com/d/msg/snabb-devel/I_3dJvfl7gY/YHgHVzjMq0kJ
Second problem: The Makefile had overlapping rules for building the SIMD code and this causes warnings to be printed. That is because the default build rule applied to these files but then we also had specific rules. This is solved now because the arch/ directory is …

Move SIMD code into arch/avx2.c and arch/sse2.c

---

src/apps/intel/intel10g.lua
src/apps/intel/intel_app.lua

I need to be able to configure the MTU of individual interfaces. This requires functionality to pass configuration options down to the driver. I suggest a simple method, where the config supplied to Intel82599 is passed on to the intel10g module unchanged.
There is no consesus about what should be included in the MTU among vendors. For example, IOS does not include the Ethernet header, while IOS-XR and JunOS does.  Others include the CRC as well. I suggest the convention to include the Ethernet header but not the CRC.
Finally, I've added support for most of the objects in the ifMIB and interfaces MIB, which makes it possible to monitor an interface with standard tools.

Enable MTU configuration and add SNMP objects to intel10g driver

---

src/README.md.src
src/apps/basic/basic_apps.lua
src/core/app.lua
src/program/snabbmark/snabbmark.lua

Previously the links for apps were accessible only by name
e.g. input.rx or output.tx. Now they are available both by name and by
number e.g. input[1] or output[2]. The exact order is not fixed.
This makes it easy to write apps that don't care what their links are
called. If there is only one link then it can be accessed as input[1].
If there are many links they can be accessed with an ipairs() loop.
The relink() method of apps is also removed. The only way that it was
actually used was to emulate this behavior in a more complex way. That
code is also removed now from basic_apps and snabbmark.
This may resolve the question: what should an app name its input and
output links in cases where it does not actually matter? Now instead
of having to choose an arbitrary name like 'rx' or 'input' …

core: Use the array part of app.input and app.output tables

---

src/core/memory.lua

If huge page allocation fails then do one of two things:
- Increase sysctl kernel.shmmax if the maximum shared memory
allocation size is less than the size of one huge page. (That is a
misconfigured kernel from our perspective.) Fixes #366.
- Increase sysctl vm.nr_hugepages otherwise to have the kernel reserve
a new huge page that we can allocate. (Try this up to three times
per allocation, as before.)
To change system-wide sysctl values is a fairly presumptuious thing to
do. For this reason we now print clear messages about what we are doing:
[memory: Enabling huge pages for shm: sysctl kernel.shmmax 1000000 -> 2097152]
[memory: Provisioned a huge page: sysctl vm.nr_hugepages 0 -> 1]
[memory: Provisioned a huge page: sysctl vm.nr_hugepages 1 -> 2]
[memory: Provisioned a huge page: sysctl …

memory: Force the kernel to enable working HugeTLB allocation

---

src/Makefile
src/core/main.lua

To determine program name from argv[0]/argv[1] remove everything after
the first `-` or `.` character. This allows names like `snabbnfv`,
`snabbnfv-1.0`, `snabbnfv-lukes-turbo-charged-version`, `snabbnfv.linux`,
and so on.
Make the usage printout for `snabb` and `snabb -h` and `snabb --help` better:
Usage: ./snabb <program> ...
This snabb executable has the following programs built in:
packetblaster
snabbmark
snabbnfv
snsh
For detailed usage of any program run:
snabb <program> --help
If you rename (or copy or symlink) this executable with one of
the names above then that program will be chosen automatically.
The program list is determined automatically by the Makefile.

main: Improve command-line handling and usage string

---

src/apps/intel/intel10g.lua
src/core/lib.lua
src/lib/hardware/register.lua

Merge Alex's support for 64-bit RC registers in the Intel driver and its SNMP support (#475).
Also disable the ancient kludge of calling `jit.off()` in the `register` module.

64bit registers merge

---

src/apps/intel/intel10g.lua
src/core/lib.lua
src/lib/hardware/register.lua

I propose to introduce a new register type called RC64, which allows access to two consecutive 32-bit registers in the case of 64-bit byte and octet statistics registers. This is legal according to section 8.2.3.23 of the spec.
At the same time, the accumulator for both types of RC registers is promoted from a Lua number to a uint64_t cdata object.  In addition to allow maintaining high-capacity counters based on 32-bit registers (e.g. packet counters), this also avoids conversions from integers to doubles.
The second commit in this PR applies the new register type to maintain HC counters in the interface MIB.
I'm a bit worried about the `jit.off()` in the readrc() method of `lib.hardware.register`. It causes blacklisting of that code by the JIT, which I would rather avoid (it's not that …

Support for 64-bit RC registers

---

src/doc/branches.md

`branches.md` serves three purposes:
- Help users find out what branches exist.
- Help developers advertise their branches.
- Help to automatically sync branches onto the SnabbCo repository.
The [Github SnabbCo/snabbswitch branches page](https://github.com/SnabbCo/snabbswitch/branches/all) shows the current status of all these branches with respect to master. Users should automatically receive all branches when pulling from the main repository.
This is intended to help new long-lived branches to be used and develop features that can synchronize with master and other branches over time.
Notes:
- There is currently a small cronjob using this file to automatically push changes from known branches onto the master repository.
- If you are the maintainer of a known branch then your pushes will …

Added doc/branches.md: List of active development branches

---

src/program/snabbnfv/neutron_sync_agent/neutron_sync_agent.sh

Fixes a bug where diff/mv commands depend on current directory.

neutron_sync_agent.sh: Fix to use qualified paths

---

src/program/snabbnfv/neutron_sync_master/neutron_sync_master.sh

Make sure that *.sql table definitions are checked into the repository.

neutron_sync_master: Include *.sql table definitions

---

src/doc/branches.md
src/doc/git-workflow.md

Define a new Git workflow that is supposed to make life easier for users, contributors, application developers, and maintainers. Specifically aim to keep `master` stable for users and application developers and create a new `next` branch 
I know everybody surely has "git workflow fatigue" by now. Sorry. This is an attempt to solve an important problem: relieve the tension between providing a stable base and quickly bringing in new code for wider testing. I am not satisfied with the old workflow of landing individual new changes directly on master: it creates an awkward compromise of somewhat stable code landing at a somewhat reasonable pace.
@eugeneia and I will have to work out how to properly fit this into the release workflow.

Document git workflow with new 'next' and 'fixes' branches

---

src/core/snabbswitch.c
src/core/startup.lua

Loading the core.main module is now wrapped in a `pcall()` to catch and report errors.
Previously errors occurring early during startup would cause a silent exit.
This should help to diagnose problems such as the one affecting #483.

snabb: Detect errors during startup

---

src/Makefile

`basename -a` seems be a relatively new feature of GNU coreutils that is not available in recent Debian releases.
Resolves #505.

Makefile: Avoid nonportable 'basename -a'

---

src/program/snabbnfv/selftest.sh

The selftest would sporadically fail with "ND failed". This was caused by a delay in applying the tunnel config and kicking of the NS.

[nfvconfig] selftest: retry the ND check a few times

---

src/apps/vhost/vhost_user.lua

Fixes #539 by simply printing "Not connected" when reporting in unconnected state.

[vhost_user] Do not crash when `report()' is called while unconnected.

---

src/lib/ipc/fs.lua

Before creating the PID subfolder, ensure the root folder exists.

Ensure /var/run/snabb exists

---

src/program/snabbnfv/traffic/traffic.lua

[snabbnfv traffic] Fix bug where in benchmark mode, engine.breaths was attempted to be accessed directly.

In snabbnfv traffic (benchmark mode) use core.counter to read engine.breaths

---

src/Makefile

Regularly scheduled monthly update of pflua to the latest version. (Just pulling from the master branch unless/until upstream suggest something else.) Can be reverted or updated before release if needed.
Changes:
```
$ git shortlog --no-merges 275239..5e2c56
Andy Wingo (28):
Simplify lexer self-tests
Add address-of pflang extension
Add parser for "pfmatch" language
Add "otherwise" test; better comments
Implement pfmatch expander.
Add doc/fail-fail.md to test { if foo fail fail } optimization
More pfmatch language updates.
Add optimizer support for 'call'
Fix pfmatch parser for LogicalExpression
ANF lowering supports "call"
Add SSA support for tail calls
Backend supports tail calls
pfmatch: allow underscores in procedure names
Add pfmatch documentation
A couple of doc fixups
Fix "fail" …
```

deps/pflua: Upgrade to latest master (5e2c56b)

---

src/README.md
src/README.md.src
src/core/app.lua
src/program/packetblaster/packetblaster.lua

Fix a performance regression bug: packetblaster peaked at around 3 Mpps because the default TX ring size has shrunk. Now sends more aggressively (around 12.8 Mpps on Interlaken).
The packet rate should actually be higher for 64-byte packets but that is another matter. This change fixes the specific regression.
See also #547 and #530.

packetblaster: Fix TX starvation bug

---

src/apps/vhost/vhost.h
src/apps/vhost/vhost_user.h

Switch to stricter C declarations to ensure that the memory layout of vhost-user requests matches the vhost-user specification. For example, use 'uint32_t' instead of 'unsigned int'. Add __attribute__((packed)) to struct declarations.
This is to ensure that the on-the-wire memory layout follows the vhost-user spec rather than the C compiler. Inspired by #560 and *may conceivably* be helpful there.
vhost-user spec:
https://github.com/qemu/qemu/blob/master/docs/specs/vhost-user.txt

vhost.h, vhost_user.h: Use more explicit types

---

src/program/snsh/README
src/program/snsh/snsh.lua

Support using `snsh` as an entry point to any snabb program. This way you can use snsh for pre-execution configuration such as enabling profiling or JIT tracing.
Here is an example of running `snabbmark` after enabling profiling:
$ sudo ./snabb snsh -jp=3F -p snabbmark basic1 1e6
Processed 1.1 million packets in 0.09 seconds (rate: 12.7 Mpps).
25%  link.lua:full < link.lua:transmit < basic_apps.lua:method
13%  freelist.lua:freelist_add < packet.lua:free_internal < packet.lua:free
13%  freelist.lua:allocate < packet.lua:clone < basic_apps.lua:method
13%  packet.lua:free < basic_apps.lua:method < app.lua:with_restart
13%  link.lua:receive < basic_apps.lua:method < app.lua:with_restart
13%  packet.lua:clone < basic_apps.lua:method < app.lua:with_restart
13%  app.lua:breathe < app.lua:main < …

Add 'snsh -p' argument to run a different program

---

src/lib/hash/base.lua
src/lib/hash/murmur.lua

Performance of lib.hash.murmur is improved by reducing the number of
memory accesses to process the "tail" portion of the data.  Current
benchmarks indicate that a pass over a 6-byte value (e.g. an Ethernet
MAC address) takes about 15 CPU cycles with MurmurHash3_x64_128 and
about 19 cycles with MurmurHash3_x86_32, provided that all constants
are pre-loaded into registers.
The base class is changed to make sure that the same CTYPE is used for
allocating the storage that holds the result of a hash function.  The
previous code, which generated distinct CTYPEs, lead to subtle
performance issues due to side-exits being taken in compiled code when
CTYPE-checking guarded instructions failed.

Speed up Murmur hash functions

---

Makefile

The files `deps/*.vsn` have to be removed or else the dependencies may not be rebuilt.

Makefile "clean" fix

---

src/lib/protocol/ipv4.lua

Stumbled over this while verifying the test-case of PR#580 with an alternate method.

Fix bug in IPv4 pseudo-header construction

---

src/Makefile

This target updates and rebuilds the required git submodules. The Makefile tells you to run this when it detects that the submodule versions are not in sync with the source code.
This is a more streamlined version of the previous behavior where the Makefile would suggest running a series of commands to update you submodules. Now 'make submods' has the same effect.
Fixes #584.

src/Makefile: Add 'make submods'

---

src/program/snabbnfv/traffic/README
src/program/snabbnfv/traffic/traffic.lua

The new `snabbnfv traffic --busy` (`-b`) option makes the traffic process run in a busy-loop.
This minimizes latency but always consumes 100% CPU.

snabbnfv traffic: Added -b/--busy option

---

src/Makefile

The new upstream source for the LuaJIT submodule is the 'snabb' branch at:
http://github.com/SnabbCo/luajit
This submodule update includes the latest fixes from Mike's v2.1 branch and also these new extensions:
1. SnabbCo/luajit#5: Support profiling at trace granularity.
2. SnabbCo/luajit#6: Support for perf events to drive the profiler.
These are extensions that have been used by Snabb developers in the past and are now made available by default.
This is motivated in part by Mike Pall encouraging the community to take over development and maintenance of LuaJIT:
https://groups.google.com/d/msg/snabb-devel/CgZEDWfIyo8/t_Q5WdsZCgAJ

deps/luajit: Switch to own snabb branch

---

src/doc/branches.md

Remove the lukego/nfv branch.
My Snabb NFV development is currently targeted at the master branch. In the future I am interested in having a larger network of NFV-related branches, e.g. a long term stable branch, but that can be added later in cooperation with other interested people.

branches.md: Remove obsolete lukego/nfv branch

---

src/lib/hardware/pci.lua

Recognize the PCI ID of the Intel X540 controller and map it to the intel_app.
This is somewhat experimental: the X540 is a new Ethernet controller that is supposed to be compatible with 82599 but we don't have much experience yet.
Based on this snabb-devel post by Chaitanya Lala:
https://groups.google.com/forum/#!topic/snabb-devel/tT_SfXMNxxI

lib.pci: Support Intel X540 with intel_app

---

src/lib/protocol/ipv4.lua
src/lib/protocol/tcp.lua

It took me a while to figure out how to use the checksum methods in ```lib.protocol.ipv4``` and ```lib.protocol.tcp``` to calculate the checksum of a packet. I decided to add two selftest functions to verify the checksum calculation is correct. The main purpose is to show how to use the ```checksum``` functions.

Add TCP and IPv4 checksum calculation tests

---

src/lib/protocol/ipv4.lua

The version/header length/TOS field is 16 not 32 bits wide.
Also add a self-test.

Fix ipv4 header initialization.

---

lib/luajit/src/jit/p.lua
lib/luajit/src/lib_jit.c
lib/luajit/src/lj_profile.c

This is a patch written by Mike Pall that makes the profiler "v"
option report the time used by each trace separately. This can be used
to decide which traces to analyze when profiling large programs.
Example:
$ ./luajit -jp=v ../test.lua
47%  TRACE 1
43%  TRACE 2
6%  Interpreted
3%  Garbage Collector
Originally posted by Mike on the LuaJIT mailing list:
https://www.freelists.org/post/luajit/Profile-at-trace-granularity,1

[LuaJIT] jit.p: Add support for profiling at trace granularity

---

lib/luajit/src/jit/p.lua
lib/luajit/src/lj_profile.c

This profiler mode samples based on a specific CPU performance event (cache-misses, branch-misses, etc) instead of wall-clock time.
Usage example:
-jp=S[cache-misses]
Implementation by Antonio Nikishaev (@llelf).

[LuaJIT] jit.p: Add CPU performance counters as profiler source

---

lib/luajit/src/jit/dump.lua
lib/luajit/src/jit/p.lua
lib/luajit/src/lib_jit.c
lib/luajit/src/lj_profile.c

This change prints more information when profiling at trace granularity. The idea is to make it easier to audit the runtime behavior of your apps: how many traces do they compile into, how are those traces connected together, and which execution path does each trace represent.
This PR builds on #619 and contains the code previously described in issue #611.
More detail with examples:
Previously the 'v' mode would print a terse summary. For example when profiling the rate_limiter app selftest:
```
$ sudo ./snabb snsh -jdump=+rs,x -jp=v -t apps.rate_limiter.rate_limiter
47%  TRACE 16
22%  TRACE 15
11%  TRACE 14
10%  TRACE 12
4%  TRACE 18
4%  TRACE 24
```
More information is shown with this change:
```
$ sudo ./snabb snsh -jdump=+rs,x -jp=v -t apps.rate_limiter.rate_limiter
47%  TRACE  16 …
```

[LuaJIT] jit.p: Enhance 'v' profiler mode

---

lib/luajit/src/lib_jit.c
src/lib/traceprof/traceprof.c
src/lib/traceprof/traceprof.h
src/lib/traceprof/traceprof.lua
src/program/snsh/snsh.lua

This is a new profiler designed to help understand LuaJIT trace behavior and performance.
You can test it with `snabb snsh -jtprof ...` combined with `-p` (run a program) or `-t` (run a selftest) or `-e` (run a Lua expression) or directly on a script file.
This is similar to our enhanced `-jp=v` support (#621) but seems to give more accurate results. Specifically when "back testing" on lukego/blog#8 the information from traceprof is consistent with the analysis:
```
traceprof report (recorded 10583/10583 samples):
62% TRACE   3               counter2.lua:5
26% TRACE   4      (3/5)    counter2.lua:9
10% TRACE   3:LOOP          counter2.lua:5
```
while the `jit.p` result is completely misleading:
```
100%  TRACE   3          ->loop     counter2.lua:5
```
which seems to be due to limitations …

traceprof: a new trace-oriented profiler for LuaJIT

---

src/Makefile

Snabb Switch is supposed to compile to a 1MB binary but recent
releases have grown to 2MB. This happened gradually as we added a lot
of valuable extensions: pflua, ljsyscall, Intel CPU PMU definitions,
and more built-in programs. This is all fine and good but we ought to
get back within our budget.
This change addresses that with UPX whole-program compression:
http://upx.sourceforge.net/
The normal way to build Snabb Switch (./snabb) is not affected:
$ make
...
BINARY    2.0M snabb
but you can use other Makefile targets to create (compressed) binaries
for distribution. The targets are bin/snabb, bin/snsh,
bin/packetblaster, and so on for each available program:
$ make bin/snabb
...
BINARY    608K bin/snabb
This requires upx to be installed. On Ubuntu 'apt-get install upx'.
The release …

Makefile: Shrink 'snabb' from 2MB to 0.6MB with UPX

---

src/lib/pmu.lua
src/lib/pmu_x86.dasl

1. Fix a crash-bug where generated dynasm assembler code could be garbage collected. This would trigger when `pmu` tries to execute the machine code that snapshots the counters.
2. Make `pmu.report()` operate on a plain table of results rather than an FFI object. This makes it easier to post-process before printing them e.g. taking a delta of two runs.

Improvements to lib.pmu (CPU Performance Monitoring Counter)

---

src/apps/intel/intel10g.lua

Enable the "TX descriptor prefetching" feature. This is required for the 82599 NIC to achieve line-rate transmission with 64-byte packets.
Resolves SnabbCo/snabbswitch#622.

intel10g: Enable TX prefetch for 14.8 Mpps

---

src/program/snsh/README
src/program/snsh/snsh.lua

Now you can run any Snabb-based program in a mode that supports
interrupting it with the keyboard (Control-\ i.e. SIGQUIT) such that
it leaves the breathe loop and enters an interactive read-eval-print
loop (REPL). Here you can poke around with arbitrary Lua expressions
and finally return back to the engine by pressing Control-d (EOF).
The `snsh` argument -q (--sigquit-repl) enables a timer callback in the
engine that checks if SIGQUIT has been received and starts a
REPL. This can be combined with the -p (--program) argument to run
another program such as packetblaster or snabbnfv.
For example:
snabb snsh -q -p packetblaster replay 64.cap 0000:01:00.0
will run packetblaster but with the hook enabled such that each time
you press Control-\ the process will receive a SIGQUIT and enter the …

snsh: Added '-q' to break program to REPL via keyboard

---

src/README.md
src/README.md.src

Explain the algorithm for updating the app network when `engine.configure()` is called multiple times.

src/README.md: Document engine.configure() reconfiguration

---

src/lib/pmu.lua

If we are unable to write an MSR (machine specific register) via `/dev/cpu` then print the full name of missing device file.

lib.pmu.writemsr(): Improve error message

---

src/dasm.lua
src/dasm_mm.lua
src/dasm_proto.h
src/dasm_x64.lua
src/dasm_x86.h
src/dasm_x86.lua
src/dynasm.lua

This is an upgrade to DynASM 1.4 which adds AVX2 instructions by corsix. It's also a multi-way merge:
- the [upstream DynASM Lua mode](https://github.com/luapower/dynasm) was rebased to DynASM 1.4
- snabb changes that were not yet added to LuaJIT DynASM (RDPMC instruction) were added too (I will make a PR to LuaJIT with that)
- snabb was then updated with the final files (and dasm.lua was changed back to load the dasm linker statically)
I ran dynasm_demo on 3 platforms but these are demos not exhaustive tests so...

DynASM 1.4 upgrade/merge

---

src/apps/intel/intel10g.lua
src/apps/ipv6/nd_light.lua
src/core/lib.lua
src/lib/protocol/ethernet.lua
src/lib/protocol/gre.lua
src/lib/protocol/icmp/header.lua
src/lib/protocol/ipv4.lua
src/lib/protocol/ipv6.lua
src/lib/protocol/keyed_ipv6_tunnel.lua
src/lib/protocol/tcp.lua
src/lib/protocol/udp.lua

This changeset covers three issues
* Caching of `bit` in `lib.lua`
* Use of native Lua endian conversion
* Logging facility
* Rate-limiting of discard messages
* Expose logger defaults in the API
* Use logging in `intel10g` and `nd_light`

lib.lua tweaks

---

src/apps/socket/raw.lua
src/apps/vpn/README.md
src/apps/vpn/README.md.src
src/apps/vpn/vpws.lua

The motivation of this patch is to avoid potential problems because of using MAC addresses with special meanings. For instance, I recall a performance bug because of using a MAC address starting with '01:', which means multicast.
An all zero MAC address is a unicast globally administered address. According to [1], addresses with starting with '00:00:00' are reserved. I think is better to use one of the four family types of unicast locally administered MAC address available in the MAC address space: X2-XX-XX, X6-XX-XX, XA-XX-XX or XE-XX-XX. In this patch I picked 02:00:00:00:00:00.
[1] http://www.iana.org/assignments/ethernet-numbers/ethernet-numbers.xhtml

Replace all-zero MAC address for 02:00:00:00:00:00

---

src/core/lib.lua
src/lib/hardware/register.lua
src/lib/macaddress.lua
src/lib/protocol/ethernet.lua

Some regular expressions use a customized regular expression [0-9a-fA-F] to match hexidecimal numbers. It is possible to use Lua's %x wildcard to do the same.
http://www.lua.org/pil/20.2.html

Use %x wildcard where possible

---

src/apps/ipv6/nd_light.lua

This fixes a “use after free” bug (#643) in nd_light. The bug only surfaced when using the Solarflare driver but is indeed unrelated. I want to highlight a pattern that I think is close to a whole class of bugs:
```
function nd_light:stop ()
packet.free(self._next_hop.packet)
+   self._next_hop.packet = nil
packet.free(self._sna.packet)
+   self._sna.packet = nil
end
```
So what I did here previously (I wrote the bug in the first place) is to free “static” packets when the app is stopped. In itself this is important as to not leak memory. The nd_light app specifically launches a timer that will send `self._next_hop.packet` periodically. What happens when you start nd_light and stop it right away? The timer gets activated, the packet is freed, the timer runs, attempts to clone a packet …

nd_light: Fix use after free bug in neighbor solicitation.

---

src/lib/hardware/README.md
src/lib/hardware/README.md.src
src/lib/hardware/pci.lua
src/program/packetblaster/packetblaster.lua

Proposed alternative to #657 after tomatoes were thrown in response to my more complicated proposal.
Adds these two functions:
- `pci.canonical(address)` => returns address in short canonical format (`01:00.0`)
- `pci.qualified(address)` => returns address in fully qualified format (`0000:01:00.0`)
with the intention that users can specify either format and Snabb Switch will prefer the canonical format internally but expand to the qualified format when needed (e.g. for resolving sysfs paths).
This is a user visible change. The PCI device scan and selftest now uses canonical addresses:
$ sudo ./snabb snsh -t lib.hardware.pci
selftest: pci
pciaddress    vendor  device  interface  status    driver      usable
01:00.0       0x8086  0x10fb  p1p1       down      apps.intel.intel_app yes
01:00.1 …

lib.pci: Support short/canonical ("01:00.0") PCI addresses

---

src/lib/pmu.lua

There were two bugs in the PMU code.  The first was that if the events
you select matched more than pmu_x86_ngeneral counters, the set of
events was being incorrectly truncated.  This would later manifest as an
error when we try to do defs[set[j+1]], as some random element in the
middle of `set' could be nil.
The other bug was that the global IA32_PERF_GLOBAL_CTRL register wasn't
being initialized.  One symptom could be that any given counter wasn't
counting -- for me it was the cycles fixed-function counter.  We didn't
observe this in the past because this is global state that could have
gotten initialized by any other program -- perhaps a previous invocation
of `perf`.

Fix bugs in PMU code

---

lib/luajit/src/lib_jit.c

So it gets rid of the warning:
```
lib_jit.c: In function ‘lj_cf_jit_util_traceinfo’:
lib_jit.c:303:32: warning: passing argument 4 of ‘setintfield’ makes integer from pointer without a cast
setintfield(L, t, "mcode", T->mcode);
```
`T->mcode` is a _void*_, size of _long_ is wide enough to hold a _void*_.

Cast T->mcode when passed as argument in setintfield

---

gcc-preinclude.h
src/apps/solarflare/ef_vi.h
src/apps/vhost/vhost_user.c
src/core/lib.c
src/core/memory.c
src/lib/traceprof/traceprof.c

Minor portability fixes that let Snabb build under Musl libc, tested on Alpine Linux.

Fix build with Musl libc

---

README.md

Fix: had missed the 'replay' argument.
Update: use shorter canonical PCI device name (without leading 0000:).

README.md: Fix and update packetblaster example

---

src/core/app.lua

This PR supersedes #633 and fixes a regression that broke app reports when `use_restart` is `true`.

core.engine: Enable selftest() method, fix app reports with use_restart = true

---

Makefile

PREFIX is usually used to indicate installation in /, /usr or /usr/local, while DESTDIR is used when creating packages etc. This is how autocrap does it and a lot of packagers expect this behavior.

make PREFIX work like expected, and use DESTDIR for that

---

src/core/lib.lua
src/program/snabbnfv/neutron2snabb/neutron2snabb.lua

`lib.load_string` failed to properly call Lua's `loadstring` built-in.

Fixed a bug where string couldn't be app arguments

---

src/core/app.lua

Raise a specific error instead of allowing a bad value to propagate in the engine (leading to a more confusing error message).

engine: Detect bad return value from app start() method

---

src/apps/socket/raw.lua

The `syscall.util.if_nametoindex()` only needs to be passed the name of the interface. The version of the function which accepts an open socket as second argument is internal to `ljsyscall`, and not even exported to client code.
Also, this moves the call to `syscall.util.if_nametoindex()` to the top of `RawSocket:new()` to simplify error handling: this way one less explicit call to `syscall.close()` is needed in case of errors.

Pass only interface name to syscall.util.if_nametoindex()

---

src/core/memory.c

Use the appropriate pointer type `uintptr_t`.
A 32bit build will fail with the following error due to -Werror:
```
core/memory.c: In function 'virtual_to_physical':
core/memory.c:36:16: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
virt_page = ((uint64_t)ptr) / 4096;
^
...
core/memory.c:51:5: error: format '%lx' expects argument of type 'long unsigned int', but argument 4 has type 'uint64_t' [-Werror=format=]
core/memory.c: In function 'allocate_huge_page':
core/memory.c:93:26: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
realptr = shmat(shmid, (void*)virtual_address, 0);
^
```
This patch is split out from #483, and fixes the problem by using an int type that changes size with the page size.

page pointers portable to 32bit platforms

---

src/README.md
src/README.md.src
src/lib/virtio/net_device.lua

Streamline the core.memory API:
- Rewrite the blurb.
- Keep dma_alloc() and virtual_to_physical().
- Remove dma_min_addr and dma_max_addr (unused).
- Deprecate huge_page_size (used but should it be?)
Backstory here is that the core.memory module has exported low-level information to other modules: the VFIO module (since removed) that needed to whitelist all DMA memory with the kernel, a /dev/vhost-net accelerator for tap devices (since removed) that also needed to whitelist all packet memory, and to a lesser extent the vhost-user implementation (that is still alive and well but may be overusing the memory API e.g. in dead code that should be removed).
Adding the deprecation note on "huge_page_size" may or may not be a good idea. Have to look more closely at the usage and clarify with a …

Simplify core.memory API

---

src/core/main.lua

Rework the parsing of the Snabb command line to allow us to ship
a nicely named snabb-lwaftr binary, but have it map internally to the
also nicely-named 'programs.lwaftr' module tree.  Gets rid of the
nasty "snabb" name duplication in the module tree.

Map `snabb-lwaftr' argv[0] to programs.lwaftr

---

src/core/lib.lua

Cdata values are equal if they have the same size and their bytes are
the same.

lib.equal can compare cdata

---

Makefile

Run as "make dist" to generate snabbswitch-`git describe`.tar.xz, which
will contain source code and a built binary.
Set DIST_BINARY to rename the binary.  Set PACKAGE to rename the
package.

Add "dist" target to makefile

---

src/doc/testing.md

Otherwise I get `core/shm.lua:111: Unable to create /var/run/snabb: Permission denied`

tests require root access

---

src/core/counter.lua
src/core/link.lua
src/core/shm.lua

Currently shm.map() will create the file and any containing directories
if it does not exist.  This is not so great, so I split it into separate
open() and create() functions, adapt all callers, and remove map() from
the public interface of the shm module.

Replace shm.map with separate create() and open()

---

src/README.md
src/core/app.lua
src/core/counter.lua
src/core/histogram.lua
src/core/link.lua
src/core/shm.lua
src/program/top/top.lua

This commit adds a histogram facility that can record the distribution
of different sampled magnitudes.  In particular, it is useful for
recording distributions of times.  Histograms can be mapped into
/var/run/snabb, where they can be analyzed by a separate process.
This commit also wires up the app.breathe() loop to record latencies for
its breath cycles into a well-known
file (/var/run/snabb/PID/engine/latency), and wires up "snabb top" to do
some basic statistics on this data.
A follow-on to #777 rebased onto #794.

Add core.histogram, use it to measure latency of app.breathe()

---

src/program/snabbmark/mp.lua

Following on from #808...
The command-line argment -e / --events already existed but now it is actually implemented.
The report is only printed by child process #0 based on the assumption that all children would tell the same story.
Just for a taste here is a little script to run the benchmark with different events and process counts:
```
#!/usr/bin/env bash
for processes in 1 2 3; do
for events in 'l2_rqsts' 'l2_trans' 'mem_trans_retired[.]load_latency_gt_' 'cycle_activity'; do
echo "@@@@ processes $processes"
echo "@@@@ events $events"
sudo ./snabb snabbmark mp-ring --packets 10e6 --processes "$processes" --events "$events"
done
done
```
See this [gist](https://gist.github.com/lukego/180e39ec4379c45fb194) for the raw output of the first run.

snabbmark: Add PMU support to mp-ring benchmark

---

src/core/link.h
src/core/link.lua
src/program/snabbmark/mp.lua

A problem with the current `struct link` and multiple processes is that the `read` and `write` members of the struct are read and modified every single time a packet is queued or dequeued.
http://dl.acm.org/citation.cfm?doid=1345206.1345215 (FastForward for efficient pipeline parallelism: a cache-optimized concurrent lock-free queue ) talks about this, and proposes improvements.
The easy improvement is to make the producer and consumer able to operate more independently by putting some control information into the data.  This is academic-speak for using a null pointer data value to indicate whether there is data available in the ring buffer.  This way, producers only have to look at `write` and consumers only have to look at `read`, and if we arrange for these members to be on separate …

[wip] multi-process ring buffers

---

src/scripts/snabb_doc.sh

This updates`scripts/snabb_doc.sh` to work with #829, while still supporting pre-#829 PRs.

Update scripts/snabb_doc.sh for #829

---

src/core/snabbswitch.c

Provide a clear compilation error on platforms that don't have a 64bit integer size, for example i386. Include a link to porting information so that the user will understand that this is not an arbitrary
restriction.
This does not work: I did not formulate the C preprocessor directive correctly. Can somebody tell me how to write it in a way that works?
This depends on the `porting.md` document from #712 to land upstream.
See also #700 #750 cc @kbara.

snabbswitch.c: Compile error on non-64bit platforms

---

src/doc/documentation-guide.md

This updates the documentation guide according to #743 and also adds a section that talks about general writing style. I came up with this section today based on my own experiences with reading and writing documentation, so it might be controversial and not what we want for Snabb Switch documentation. Feedback welcome!

Update documentation guide

---

src/apps/pcap/pcap.lua

I was getting an error, `file` is nil, due to a permissions problem:
```
lib/pcap/pcap.lua:36: attempt to index local 'file' (a nil value)
stack traceback:
core/main.lua:122: in function '__index'
lib/pcap/pcap.lua:36: in function 'write_file_header'
apps/pcap/pcap.lua:36: in function 'new'
core/app.lua:165: in function <core/app.lua:162>
core/app.lua:201: in function 'apply_config_actions'
core/app.lua:110: in function 'configure'
```
Printing out the error status `io.open` returns in case couldn't open a file can be helpful to figure out what is going on:
```
compiled binding table ../data/binding-table.o is up to date.
apps/pcap/pcap.lua:35: /tmp/endoutv4.pcap: Permission denied
stack traceback:
core/main.lua:122: in function <core/main.lua:120>
[C]: in function 'error' …
```

Print out error message in case PCAP app couldn't open file

---

src/doc/branches.md

Register two new branches for collecting and integrating feature branches that incrementally create a couple of large new features:
- `mellanox`: Collect the changes for ConnectX-4 support until ready for master. See #706.
- `multiproc`: Collect the changes for multiple process parallel processing until ready for master. See #722.
The main intention of creating integration branches is to make it easier to break down the development into smaller independent pieces and have a place where we can fit them together.
I propose to be the subsystem maintainer for `multiproc` and `mellanox` branches. So if somebody sends a PR on these topics then I would be the upstream person merging it onto the appropriate branch. Then once the branch as a whole is in good shape I would send a PR and ask …

branches.md: Add mellanox and multiproc branches

---

src/doc/branches.md

See #802 for the lwaftr merge.  The current HEAD of the `lwaftr` branch is the same as the current HEAD in that PR.  `lwaftr` will be the development head for new lwaftr development and will not be rebased.  We will merge in from `master` monthly, and will propagate changes back to master through `kbara-next`.
The only big open question to manage for me is how to manage changes to core.  Obviously we will try to avoid them, but let's say we need an urgent fix to something in core and have no time to talk about it with upstream.  What do we do?  Do it in `lwaftr` directly and hope that we'll be able to submit upstream, or revert by the time we go to send to `kbara-next`?  Switch development to a new branch and sort things out later?  To me it's not quite clear.  Suggestions welcome :)

Add lwaftr branch.

---

src/scripts/snabb_doc.sh

I added a new cron job “SnabbDoctor” to davos that will render and publish HTML renderings of our documentation.
1. the current release's documentation can be found at http://snabbco.github.io/
2. a tags documentation can be found at `tag/<tag>.html`, e.g. http://snabbco.github.io/tag/v2016.03.html
3. Pull Requests have a new status that points to the documentation for that PR at `sha1/<sha1>.html`

Add scripts/snabb_doc.sh

---

src/doc/style.css

This is a change to the HTML manual stylesheet that puts the table of contents into a fixed left column. I feel this improves the UI for browsing the docs on a desktop computer or laptop, on the other hand this change will probably make things worse on mobile/tablets. I expect this to be controversial, and this is certainly not the end-all, be-all of stylesheets.
*Before:*
*After:*

doc/style.css: Put ToC into a left column

---

src/doc/branches.md

This branch has already been informally registered via discussions on Github and this commit makes it official (and enables mirroring to the SnabbCo repo).
cc @kbara

branches.md: Add kbara-next

---

src/doc/branches.md

Register my `pdf-manual` branch in branches.md.
The short-term objective of this branch is to create a high-quality PDF manual by whatever means necessary. That can include integrating separately contributed chapters of documentation, editorializing by documentation how things *should* be rather than how they are right now, etc. I will be satisfied when I can put a nice copy of the documentation up on [Lulu](http://lulu.com).
This will feed upstream towards `documentation-fixes` and will likely require some edits before it is accepted there.
The long-term objective could be to maintain the PDF edition of the manual e.g. ensure that it builds cleanly and has no glaring formatting problems.
Content:
BRANCH: pdf-manual git://github.com/lukego/pdf-manual
Maintenance branch for the PDF edition …

branches.md: Add branch pdf-manual

---

src/doc/branches.md

Adds a named branch for IPsec development.
#820 was the first PR to be merged into this branch.

Add ipsec branch

---

src/doc/template.latex

The LaTeX template in our tree did not work with recent versions of pandoc. The problem is essentially this one: http://tex.stackexchange.com/questions/257418/error-tightlist-converting-md-file-into-pdf-using-pandoc
This change manually replaces the generic parts of the template with the reference version found here: https://github.com/jgm/pandoc-templates/blob/master/default.latex
This may make the build incompatible with older versions of pandoc, I am not sure. I did consider dropping the custom LaTeX template entirely but decided on balance that it looks nicer and is worth spending a little effort to try and maintain.

doc/template.latex: Updated to suit recent pandoc

---

src/program/snabbnfv/doc/getting-started.md

I tried to use snabbnfv today, Good, It worked.
But in getting-started doc, there were something wrong(old?) command.
So I fixed getting-staretd.md
First, in section Run the Intel 82599 driver selftest, I couldn't use SNABB_TEST_INTEL10G_PCIDEVA/B.
I used SNABB_PCI_INTEL0/1, there worked.
Second, in section Create and launch two VMs and to launch ubuntu2,
Some ids were duprecated ubuntu1's ids, so I fixed some ids in ubuntu2 like char0 -> char1.

FIX snabbnfv getting-started.md

---

README.md

This file was missed in the previous renaming effort that was rooted in src/.

Top-level README: Rename "Snabb Switch" to "Snabb"

---

src/Makefile
src/README.md
src/doc/genbook.sh
src/scripts/snabb_doc.sh

@lukego `genbook.sh`/`make obj/doc/snabb.*` were broken and never worked correctly, we missed that because SnabbDoc does not `make clean` before building. This PR rectifies that. I recommend merging this and making it into a bug fix release, in order to make valid PRs in this release cycle pass SnabbDoc.

Fix genbook.sh

---

src/core/counter.lua

Sometimes, for instance when running tests, it is useful being able to open the same private counter multiple times in the same program.
The underlying memory is not mapped multiple times: the already existing counter is returned.

Allow opening counters multiple times

---

src/lib/ipsec/aes_128_gcm.lua
src/lib/ipsec/aes_128_gcm_avx.dasl

This fixed a memory corruption caused by an out of bounds write by the DynASM code used in `lib.ipsec.aes_128_gcm`. This patch also adds stricter type signatures to the API exported from the DynASM code which would have caught this error. Review of my C type interpretations would be appreciated (see inline comments below). The memory corruption is reproducible using the following script:
```
datagram = require("lib.protocol.datagram")
esp = require("lib.ipsec.esp")
-- When I set this to 30000 it runs fine
local npackets = 31000
_G.developer_debug = true
io.stdout:setvbuf("no")
print("setup")
local packets = {}
print("allocate"..npackets)
for i = 1, npackets do
-- When I skip the datagram and do `plain = packet.allocate()' it runs fine
local d = datagram:new(packet.allocate())
packets[i] = …
```

Fix memory corruption in lib.ipsec.aes_128_gcm

---

src/README.md
src/README.src.md
src/core/packet.lua
src/lib/ipsec/README.md
src/lib/ipsec/aes_128_gcm.lua
src/lib/ipsec/esp.lua
src/lib/ipsec/seq_no_t.lua
src/lib/ipsec/track_seq_no.c
src/lib/ipsec/track_seq_no.h
src/program/snabbmark/README
src/program/snabbmark/snabbmark.lua

This optimizes the encapsulation and decapsulation routines provided by `lib.ipsec.esp`:
* The routines now use raw buffer mutations instead of `packet.append`, and no longer create a new packet, instead they only mutate the input packet. For this I added a function `packet.resize` that is really just a setter for `packet.length` that additionally checks for overflow.
* Following the awesome [JIT tracology research](https://github.com/SnabbCo/snabbswitch/pull/638) by @alexandergall, the branch heavy sequence number tracking is now implemented as a C function. (This is actually not a caveat, it would probably have to become a C function anyways in the course of implementing efficient anti-replay functionality.)
Benchmark results:
```
$ sudo ./snabb snabbmark esp 1e7 1024 encapsulate …
```

Optimize lib.ipsec.esp

---

src/lib/ipsec/README.md
src/lib/ipsec/esp.lua
src/program/snabbmark/snabbmark.lua

Updates API for #845 and fixes a bug in `lib.ipsec.esp.encapsulate` where input packet length was unchecked.

lib.ipsec.esp: update API and fix sanitation bug

---

README.md
src/core/main.lua
src/doc/porting.md

This is an attempt to set realistic expectations for users and developers about Snabb Switch portability both now and in the future. This is to avoid causing confusion as we have in #701 for example.
Summary:
- Added `doc/porting.md` to summarize the situation.
- Link from top-level README.
- Print a warning at startup when running on unsupported platform.
Feedback welcome!

porting.md: Add notes about Snabb Switch porting & portability

---

src/doc/code-of-conduct.md

I propose this short and sweet code of conduct for the Snabb community. This is intended proactively to frame future discussions when problems come up.
The basic suggestions here are to be civil, for upstream to act as a resource for helping people to cooperate efficiently (even when their goals don't immediately align with the master branch), and to keep important discussions on Github so that watching the project here is sufficient to stay "in the loop."
I have found it frustrating in the past to contribute to projects where the upstream community are rude, don't care whether contributors achieve their own goals, or require unproductive rituals that disrespect contributors' time.
Let's not become one of those projects. Instead let's encourage contributors to whack us on the head with …

doc/code-of-conduct.md: Add a community code of conduct

---

src/doc/trademark.md

This is a simple and permissive trademark license taken directly from
the PostgreSQL one: https://wiki.postgresql.org/wiki/Trademark_Policy.
This would make it clear that everybody is welcome to use the Snabb name and logo for diverse Snabb-related activities such as promoting software, conferences, user groups, support services, books, magazine articles, etc. This means that "Snabb" would refer to the union of all these activities.
Suitable for our project?

doc/trademark: Added tracemark policy

---

src/Makefile

Centos 6 ships with an old version of gcc that doesn't support -mavx2. It would be nice for the Makefile to respect CC rather than having to mangle PATH.

use the CC env var for gcc command in Makefile if available.

---

src/doc/testing.md
src/scripts/snabb_bot.sh

This updates @SnabbBot to merge and compare PRs to their base branches instead of master. My motivation is that given our new work flow it is useful for contributors and maintainers to “get what you see”. E.g. if I open a PR targeting the `ipsec` branch SnabbBot will no longer merge `master` (but `ipsec` instead) into that PR head before testing it.
Maintainers need to watch out for the following: an affirmative SnabbBot result no longer means that a given PR is mergable or tested with `master` *unless* that PRs target is `master`. On the upside, if you open a PR targeting `next` it will actually be tested against `next` and the SnabbBot results will be more realistic.
I have already deployed this version and it is already in effect. (Sorry if I irritated anyone with the live testing.) I …

SnabbBot: use PR base as moving target instead of master

---

src/doc/genbook.sh
src/doc/snabblab.md

Fixes #864
I've modified it a bit and added minimal `Using the lab` and `Questions` sections.
After this is merged, we should update the wiki to point to the manual.
cc @lukego @eugeneia

Import snabblab docs from the wiki into the manual

---

src/program/snabbnfv/test_env/test_env.sh

This is the last missing piece for https://github.com/snabblab/snabblab-nixos/issues/13
Motivation: on snabblab servers it's too stateful to modify home directories of all users, so we'd like snabb to pick up a specific bash environment variable to discover test fixtures needed for `make test`.
cc @lukego @eugeneia

test_env.sh: prefer $SNABB_TEST_FIXTURES over ~/.test_env

---

src/core/packet.lua

Enable a really important assertion that the packet freelist does not overflow when we allocate a new batch of packets.
This should not be a performance issue: the check is on a slow-path where we are allocating a thousand new packets.
This is actually very important. I found a bug that packetblaster would crash with heap corruption / segfault when you run it with more than 3 network interfaces at the same time. This is because it allocated too many packets for transmit/receive buffers and that error was not caught unless "developer debug" mode was enabled.
(That problem is separately alleviated by #883 that reduces the descriptor queues from 32K packets to 2K packets each.)

core/packet.lua: Enable overflow check when allocating packets

---

src/core/packet.lua

Packets are allocated dynamically on demand and this is only an artifical limit of "more than anybody should ever need" for catching unbounded allocations (leaks). (The limit also serves to make the freelist simple i.e. a fixed-size array.)
The previous value of 100,000 is too low to serve its purpose: it is reasonable to allocate more than 100,000 packet buffers when managing many network receive queues and wanting to avoid packet drops.
See discussion at: https://github.com/snabbco/snabb/pull/882#issuecomment-213319205

core.packet: Extend max packets from 100K to 1M

---

src/core/app.lua
src/lib/timers/ingress_drop_monitor.lua
src/program/lwaftr/run/run.lua

Moves ingress-drop-monitor out of engine and puts it on its own file as a timer. Applications can use the timer to activate packet-drop monitoring on applications that implement `ingress_packet_drops` method. In this case, ingress-drop-monitor is activated by default for the lwAFTR application.

Make ingress drop monitor a timer and enable it only in lwAFTR

---

src/apps/mellanox/README.src.md
src/apps/mellanox/connectx4.lua
src/lib/hardware/pci.lua

Currently the code covers the init procedure of the card up to QUERY_HCA_CAP which fails with "bad block number".
The init procedure so far allocates the command queue and initializes it, and there's some handy methods to send commands with input and output data. The commands are sent synchronously, one at a time (so only the first position of the queue is ever populated) and polled for completion. Later in the init procedure (this is not done!) we'll initialize an event queue and we'll be able to send commands asynchronously and use events to check for completion.
The selftest function does some testing on the bit utilities and tries to initialize the card(s) based on `SNABB_PCI_CONNECTX4[0|1]` env var(s).
The development was done entirely on lugano-4 on 100G cards.
Below is a handy …

Mellanox ConnectX-4 Driver (WIP)

---

src/apps/test/delayed_start.lua

An app that delays packet forwarding for a configurable period of time.
Useful when feeding pcaps into a physical nic. The delay lets the peer
NIC the link to come up before sending packets so none are dropped.
Waiting for a linkup in the NicDriver:new() delays the whole process
in every situation and is even worse when a port doesn't link as all the 
timers need to expire.

Delayed_start, stall snabb so that peer NIC drivers can fully initialize

---

src/lib/hardware/README.md
src/lib/hardware/register.lua

Setting the 3rd byte in a register to 45 or bits 0:3 to 5 is currently quite awkward.
This provide 2 helper methods to the Register objects to make life easier.

Add bits and bytes methods to Register

---

src/apps/basic/README.md
src/apps/basic/basic_apps.lua

2 very basic apps useful for monitoring rather than forwarding traffic.

Truncate and sample

---

src/program/snabbnfv/test_env/test_env.sh

These two changes are necessary to use NixOS as a guest image for snabbnfv selftest.
- `$SNABB_KERNEL_PARAMS` shouldn't do any harm and it's needed to pass `init=` as it has to point to nix store
- NixOS uses initrd and needs to be passed to qemu
@eugeneia what do you think is best, should we pass initrd only when assets have the file?

test_env.sh: set initrd and be able to append kernel params

---

src/lib/protocol/ipv4.lua

The error for malformed addresses in `lib.protocol.ipv4:pton` had a typo. The `address` variable didn't exist, I believe it should be the `p` parameter that has been passed to the method.

Fix malformed error typo in lib.protocol.ipv4

---

src/apps/mellanox/connectx4.lua

This PR completes the ConnectX-4 driver initialization sequence.
Next steps are transmit and receive following the plan on #706.

Completed Mellanox initialization sequence

---

src/scripts/dock.sh

Switch to using `eugeneia/snabb-nfv-test-vanilla` by default in `scripts/dock.sh`. Should have done that way earlier, but doing this now finally since #944 triggers a bug in QEMU 2.4.0. This will most likely trigger a performance regression, so it might be wise to merge this as the very end of the release cycle to avoid the regression cascading onto other PRs.
Cc @lukego

scripts/dock.sh: use eugeneia/snabb-nfv-test-vanilla by default

---

src/apps/intel/intel_app.lua
src/lib/ipc/shmem/iftable_mib.lua

The counter value for the interface speed should be in units
of bps.  The ifSpeed SNMP object must obey RFC3635 sec. 3.2.8.

Fix interface speed

---

src/core/memory.lua
src/core/shm.lua

When starting multiple snabb processes in quick succession, in for example an RSS enabled driver 2 race conditions can cause abnormal termination.

fix 2 race conditions

---

src/README.md
src/core/app.lua

I think apps should have a 'start' method. 
The event will be emitted by `ops.start` (in `core/app.lua`). This _start_ method will give a chance to apps to additionally initialize themselves. For instance, right now apps can only access their links or even their own name in `push` and  `pull`methods. The reason is that these properties are setup by `ops.start` but it doesn't emit a _start_ event to their apps. Interestingly, `ops.stop` do emit a stop event to the apps :)
The background for this change is that we want to add counters per app in the lwAFTR and the only chance we have to do that is in their `push` or `pull` methods or doing other hacks that modify the engine https://github.com/Igalia/snabb/pull/299 I think the _start_ method solution is consistent with the current design.

Add 'start' method to apps

---

src/apps/vhost/vhost_user.lua

Added a long description of the "feature cache" and how it supports reconnecting to a running QEMU.
Added a restriction so that the cache is only considered for the first feature negotiation performed by a vhost-user app instance. This is to avoid using the cached features when renegotiating with a guest e.g. when the guest has switched to a new driver.
Not yet tested! Should fix #932. cc @wingo

vhost_user: Fix & comment "feature cache"

---

src/lib/virtio/net_device.lua

Snabb could over-report the size of jumbo packets delivered to the VM under certain circumstances.
This was detected when using jumbo frames with VMs that were bootstrapped with nix. Could not be reproduced with Ubuntu guests.
I resisted the urge to refactor the virtio device code more because this will be faster and safer once we complete some related work with Hydra for testing many software combinations.

virtio/net_device: Fix bug with mergeable rx buffers

---

src/README.md
src/core/memory.lua

Now it is possible to request specific alignment for DMA memory.
This is practical. For example, Mellanox ConnectX-4 requires specific alignments (e.g. 4KB).
(cherry picked from commit f349c41973af27fbbab431736b7fb4ddc512aa8e)

core.memory: Add 'align' argument to dma_alloc()

---

src/Makefile

Otherwise it prints misleading errors:
```
grep: jit/vmdef.lua: No such file or directory
grep: program/lisper/dev-env/syscall.lua: No such file or directory
grep: program/lisper/dev-env-docker/syscall.lua: No such file or
directory
grep: jit/vmdef.lua: No such file or directory
grep: program/lisper/dev-env/syscall.lua: No such file or directory
grep: program/lisper/dev-env-docker/syscall.lua: No such file or
directory
grep: jit/vmdef.lua: No such file or directory
grep: program/lisper/dev-env/syscall.lua: No such file or directory
grep: program/lisper/dev-env-docker/syscall.lua: No such file or
directory
grep: jit/vmdef.lua: No such file or directory
grep: program/lisper/dev-env/syscall.lua: No such file or directory
grep: program/lisper/dev-env-docker/syscall.lua: No such file or …
```

src/Makefile: silence grep

---

src/program/snabbnfv/test_env/test_env.sh

Once we start using Nix fixtures, guest processes output will be also part of console output so it will be easier to see what's going on inside the guest.
cc @eugeneia

test_env.sh: output kernel console to stdout

---

src/core/timer.lua

Print debug messages only when enabled by editing the `core/timer.lua` source file, not when _G.developer_debug is enabled.
The debug mode prints a message every time a timer is executed. This could easily produce thousands of messages per second in reasonable applications. This seems appropriate when specifically debugging the timer module but not when enabling a more general debug mode.

core.timer: Inhibit debug messages

---

src/core/packet.lua
src/lib/ipsec/esp.lua

Removes some leftovers from #913 that I assume were re-introduced by merges.

core.packet: Remove leftover data/length reader functions

---

src/apps/bridge/flooding.lua

Fixes a regression in `apps.bridge.flooding` introduced by 4b4b8ad / #638. This PR supersedes #912 .

apps.bridge.flooding: Fix regression introduced by 4b4b8ad / #638.

---

src/README.md
src/apps/intel/intel_app.lua
src/apps/ipsec/esp.lua
src/apps/ipv6/nd_light.lua
src/apps/keyed_ipv6_tunnel/tunnel.lua
src/apps/packet_filter/pcap_filter.lua
src/apps/rate_limiter/rate_limiter.lua
src/apps/socket/raw.lua
src/apps/tap/tap.lua
src/apps/vhost/vhost_user.lua
src/core/app.lua
src/core/counter.lua
src/core/histogram.lua
src/core/link.lua
src/core/main.lua
src/core/shm.lua
src/lib/virtio/net_device.lua
src/program/top/README
src/program/top/top.lua

This changes quite a few things around `core.shm`, mainly to remove statistics counter boilerplate, and to conveniently support multiple types of shared memory objects (as opposed to just counters). I am not super happy with the `shm.{create,open,delete}_frame` abstraction but it does the job. Summary of changes:
- changes the runtime directory layout: there are now directories for `apps/`, `links/`, `engine/`, `pci/`. Link structs are no longer exposed. All memory mapped files now have extensions that designate their type, for e.g. `snabb top` to determine how to open them.
- snabb top now has `-l` instead of `-a`, which supports dumping engine/link counters as well
- apps no longer create/delete their shared memory directly but use the field `myapp.shm` to declare objects.
- …

Extended support for managing shared memory

---

src/apps/intel/intel1g.lua

Recently we updated our lwaftr branch with Snabb master. Since then snabb-bot CI tests are failing on intel1g selftest. Example: https://gist.github.com/lwaftr-igalia/8d3a39922142575d10dae99027e108fd
The reason is that snabb-bot runs the tests as:
```bash
nix/store/zjvf7la6my2pqshyaz71h1n9icx3bvw8-docker-1.8.1/libexec/docker/docker run \
--rm --privileged -i -v /tmp/snabb_bot/tmp/repo:/snabb -e SNABB_PCI0=0000:83:00.0 \
-e SNABB_PCI1=0000:83:00.1 -e SNABB_PCI_INTEL0= -e SNABB_PCI_INTEL1= \
-e SNABB_PCI_INTEL1G0= -e SNABB_PCI_INTEL1G1= -e \
SNABB_PCI_SOLARFLARE0= -e SNABB_PCI_SOLARFLARE1= -e \
SNABB_TELNET0= -e SNABB_TELNET1= -e SNABB_PCAP= -e \
SNABB_PERF_SAMPLESIZE=5 lwaftr/snabb-test \
bash -c mount -t hugetlbfs none /hugetlbfs && (cd snabb/src; make benchmarks)
```
`SNABB_PCI_INTEL1G0` …

Skip intel1g selftest if SNABB_PCI_INTEL1G0 is empty

---

src/core/main.lua
src/core/shm.lua

This PR adds environment variables for telling Snabb to preserve process shm objects after termination. This is particularly intended to make it possible for CI to preserve shm directories of test runs so that relevant information can be extracted post-moretem e.g. timeline logs, histograms, counters, etc.
I know that we already have too many undocumented environment variables. Sorry. I see cleaning this up as a separate matter and for now I am focused on improving CI.
- `SNABB_SHM_ROOT` can be used to override the default location of shm files (`/var/run/snabb`).
- `SNABB_SHM_KEEP` can be set to prevent removal of the shm folder when the process terminates. (The existing variable `SNABB_DEBUG` has this effect already but that also has other consequences that may not always be desirable …

Add SNABB_SHM_ROOT and SNABB_SHM_KEEP

---

src/apps/vhost/vhost_user.lua
src/lib/virtio/net_device.lua
src/lib/virtio/virtq_device.lua

This branch improves virito-net performance substantially by fixing bad cases in the performance test matrix.
- [iperf and l2fwd benchmarks](https://hydra.snabb.co/build/438946/download/2/report.html#split-by-benchmark) show more consistently high scores (dramatically so for l2fwd).
- [l2fwd by configuration benchmarks](https://hydra.snabb.co/build/438946/download/2/report.html#configuration-1) shows that the benefit comes mostly from fixing performance problems that affect specific virtio-net configuration options. This includes a big improvement for the base options negotiated by recent DPDK releases.
The vhost_user app now JITs separate machine code for each connection. The transmit and receive paths are also JITed separately.
This improves performance and consistency for many …

Use LuaJIT-fu to optimized virtio-net device

---

src/scripts/snabb_bot.sh
src/scripts/snabb_doc.sh

I noticed only yesterday that SnabbBot ignored some PRs. The issue is that SnabbBot is not aware of [GitHub’s paginated API responses](https://developer.github.com/v3/#pagination). This is only a dirty fix that should give us some leeway until we have more than 100 open PRs. SnabbBot really needs to parse the Link headers and traverse over the pages somehow.
Note to self:
```
awk '/^Link: <(.*)>; rel="next".*$/ { print gensub(/^Link: <(.*)>; rel="next".*$/, "\\1", 1) }'
```

snabb_bot: Dirty fix for GitHub API pagination

---

src/apps/vhost/vhost_user.lua

Follow the rules for the vhost-user protocol to enable and disable processing. Particularly, avoid processing DMA requests when the guest driver is offline because they will contain garbage.
This fix should resolve all QEMU-related failures in the test matrix for the l2fwd benchmark. Compare [new results](http://rpubs.com/lukego/200128) and [old results](https://github.com/snabbco/snabb/issues/976#issuecomment-236838883). Highlights that there are still a couple of DPDK-related interop problems to resolve afterwards.

vhost_user: Enable/disable vring processing on kick/get_base

---

src/program/snabbnfv/test_fixtures/nfvconfig/test_functions/filter.ports

This is to make the configuration file compatible with the "filter" benchmark configuration.
Expected to resolve the dramatic test failures seen here:
https://hydra.snabb.co/build/203152/download/2/report.html#success-and-failure

snabbnfv: Update filter.ports config to allow iperf

---

src/program/snabbnfv/test_env/test_env.sh

In master, the SnabbNFV selftest always tries to run a QEMU image regardless whether an image file exists or not. In case it doesn't exist, the process which tries to log into the VM keeps waiting until it times out with an exit error.
```
src $ sudo ./program/snabbnfv/selftest.sh
Defaulting to SNABB_TELNET0=5000
Defaulting to SNABB_TELNET1=5001
Defaulting to SNABB_IPERF_BENCH_CONF=program/snabbnfv/test_fixtures/nfvconfig/test_functions/same_vlan.ports
USING program/snabbnfv/test_fixtures/nfvconfig/test_functions/other_vlan.ports
Defaulting to MAC=52:54:00:00:00:
Defaulting to IP=fe80::5054:ff:fe00:
Defaulting to GUEST_MEM=512
Defaulting to HUGETLBFS=/hugetlbfs
Defaulting to QUEUES=1
Defaulting to QEMU=/usr/bin/qemu-system-x86_64
cp: cannot stat ‘/home/dpino/.test_env/qemu.img’: No such …
```

Skip SnabbNFV test if cannot find QEMU image

---

src/README.md
src/core/shm.lua

Trying to open a shared memory object which has not been mapped yet results in an error. For instance:
```
core/shm.lua:37: shm open error (26039/shm/selftest/obj):No such file or directory
```
I think it would be useful to have an `exists` method which could be used to check whether an object exists before trying to open it.

Add method 'exists' to core/shm

---

src/program/top/top.lua

When running top, if there are multiple snabb instances, instead of printing out "Multiple Snabb instances found. Select one", print out the list of pids as well (except current one).

Print out multiple snabb instance pids

---

src/README.md
src/core/packet.lua

#913 made the packet ctype public in documentation, but actually failed to make it publicly accessible by other code, this commit revises that.

core.packet: make packet_t public accoding to documentation

---

src/README.md
src/core/lib.lua

I believe ntohl should be unsigned and have the same semantics as C.ntohl. Switching between signed and unsigned definitions of it breaks code. Using a non-standard definition of such a fundamental function is an unnecessary trap.
This is labelled a sketch because it breaks the tests for 4 apps:
```
ERROR     testlog/lib.protocol.datagram
ERROR     testlog/apps.ipv6.nd_light
ERROR     testlog/apps.vpn.vpws
ERROR     testlog/apps.socket.raw
```
If @eugeneia and @lukego are conceptually happy with this change, I will update those 4 apps to not be broken and remove the [sketch] marker.

Make ntohl/htonl unsigned, in line with C and expected semantics

---

src/core/lib.lua

@eugeneia , you may want to add this to #1026 
These two tests should work on both LE and BE platforms,  catch any drastic ntohl breakage in the future, and take absolutely trivial time to run.

Added ntohl selftest sanity checks

---

src/apps/rate_limiter/rate_limiter.lua
src/lib/parameters.lua

Oftentimes we pass around tables of options.  Some of those options are required, some are optional.  Thing is, it becomes hard to add required options over time, as old code might not detect that it needs to change; it's also hard to let old code know when options go away; and most importantly it's easy to make typos.  It's also a bit of irritating effort to provide for optional values which default to false; the idiom `conf.foo = conf.foo or bar` is just too easy to type.
In the lwaftr and in pflua we use helpers to parse options that solve all these problems.  Maybe they're good for snabb itself?  Feedback welcome @lukego @eugeneia :)
I note that @kbara once thought this sort of thing was too much machinery, then it caught a nice bug and she became a believer :)

[sketch] Prevent typos in option tables

---

src/apps/intel/intel10g.lua
src/apps/intel/loadgen.lua
src/program/firehose/firehose.lua

Intel10g's ring buffer has to comply several restrictions (power of two and not larger than 32*1024). Currently these constraints are implemented independently in several apps (firehose, lwaftr). The PR adds a single entry point for getting/setting intel10g's ring buffer.

Getter/setter for Intel10g's ring_buffer_size

---

src/program/packetblaster/packetblaster.lua
src/program/packetblaster/replay/README
src/program/packetblaster/replay/replay.lua
src/program/packetblaster/synth/README
src/program/packetblaster/synth/synth.lua

When running packetblaster replay with _--no-loop_ switch, input pcap file is only iterated once. Duration is set to one second by default if not set.
I needed to refactor _synth.lua_ as well. The PR cleans up other necessary files too and fixes passing wrong number of arguments to _replay_.
Examples:
Packetblaster replay:
```
$ sudo ./snabb packetblaster replay -D 1 v6-10.pcap 81:00.0 81:00.1
filename=v6-10.pcap
Transmissions (last 1 sec):
apps report:
nic1
81:00.0 TXDGPC (TX packets)     2,142,717       GOTCL (TX octets)       1,186,937,244
81:00.0 RXDGPC (RX packets)     0       GORCL (RX octets)       1,186,942,230
nic2
81:00.1 TXDGPC (TX packets)     2,142,838       GOTCL (TX octets)       1,186,983,780
81:00.1 RXDGPC (RX packets)     0       GORCL (RX octets)       1,187,038,626
``` …

Add no-loop switch to 'packetblaster replay'

---

src/apps/tap/tap.lua

Further to @alexandergall comments in slack, now tap doesn't allocate/free a packet on every breath.

avoid allocating a packet on every breath

---

src/core/main.lua

@vanfstd knows his Unix and instantly spotted this nobrainer. :-)
The return value of `S.fork` was not checked, which might lead to difficult to debug crashes in some situations.

core.main: check the return value of fork.

---

src/apps/socket/raw.lua
src/apps/socket/unix.lua
src/core/lib.lua
src/core/main.lua
src/core/memory.lua
src/lib/hardware/pci.lua
src/program/lisper/lisper.lua

This adds `core.lib.assert` and exposes it globally to replace various ad-hoc `assert` re-implementations. This variant of `assert` is convenient because it calls `tostring` on its second argument, which synergizes well with ljsyscall that returns metaobjects for errors. Since Snabb is a heavy user of ljsyscall, I figured this change will benefit the overall code base. Evidence: there were multiple ad-hoc assert definitions because of this exact issue.
Depends on: #1017

Overload assert to synergize with ljsyscall

---

src/apps/vlan/vlan.lua

There are certain VLAN tags that are not correctly untagged, for instance VLAN: 128.
The problem is that VLAN tags are read as uint32. This value is compared to a tag, which is obtained as the result of a bitwise operation. As LuaJIT BitOp module works in the signed int32 range, certain tags return a negative number while being compared to an uint32, which is always a positive number.
The solution is to read VLAN tags as int32 or to read them as uint32 and to apply the `bit.tobit()` operation. `tobit()` guarantees successful comparisons between the result of bitwise operations in LuaJIT (for instance when comparing a bitwise operation to a constant). Certainly I think reading the tags as int32 is simpler.
Here is a small snippet that renders the issue:
```lua
local ffi = require("ffi") …
```

Cast VLAN tags as int32

---

src/apps/ipsec/README.md
src/apps/ipsec/esp.lua
src/doc/genbook.sh
src/lib/ipsec/README.md
src/lib/ipsec/aes_128_gcm.lua
src/lib/ipsec/esp.lua
src/program/snabbmark/snabbmark.lua
src/program/snabbnfv/README.md
src/program/snabbnfv/nfvconfig.lua
src/program/snabbnfv/test_fixtures/nfvconfig/test_functions/crypto-tunnel.ports
src/program/snabbnfv/test_fixtures/nfvconfig/test_functions/crypto.ports
src/program/snabbnfv/traffic/README

This fixes a critical bug in the ESP transport feature in Snabb NFV where the same key material was used for both streams (transmit/receive). A sanity check has been added to `lib.ipsec.esp` to make this misuse impossible.
Use of the confusing term “keymat” is avoided, key/salt is now always specified separately.
`window_size` is now automatically padded to a multiple of eight to loosen the restriction on the configuration value.
Documentation is updated and extended.
Cc @vanfstd

IPsec: update Snabb NFV integration

---

README.md

For me this is a no-brainer, we have fairly detailed documentation but no obvious public reference towards it. This puts a reference in a place where people looking for it will likely find it.

README.md: link to documentation

---

src/apps/ipv6/nd_light.lua
src/apps/keyed_ipv6_tunnel/tunnel.lua
src/apps/lwaftr/fragmentv6.lua
src/apps/lwaftr/generator.lua
src/apps/lwaftr/icmp.lua
src/apps/lwaftr/lwaftr.lua
src/apps/lwaftr/ndp.lua
src/core/packet.h
src/core/packet.lua
src/lib/ipsec/esp.lua
src/lib/protocol/datagram.lua
src/lib/virtio/net_driver.lua
src/lib/virtio/virtq_driver.lua

This builds on #1032 and uses shiftleft/shiftright in the virtio-net driver to tag and untag packets.  It also switches guest snabb applications to use direct descriptors.

Virtio uses shiftleft/shiftright to tag packets

---

lib/ljsyscall/syscall/linux/c.lua
lib/ljsyscall/syscall/linux/constants.lua
lib/ljsyscall/syscall/linux/syscalls.lua
lib/ljsyscall/syscall/linux/types.lua
src/lib/numa.lua

This PR is a distilled port of https://github.com/Igalia/snabb/pull/341 to Snabb master, adding a couple of interfaces to ljsyscall, pulling in a getcpu() bugfix from @kbara, and then adding a Snabb module that lets you do `numa.bind_to_cpu(CPU)` in Snabb.  That will bind the current thread to that CPU, bind the memory for that thread to that CPU's NUMA node, and migrate all memory to that NUMA node.  It's ideal for hooking up to a `--cpu` command-line argument, with no `taskset` / `numactl` shenanigans, and with the additional benefit of migrating pages.  (That's what we do in the lwaftr; this commit is from Igalia/lwaftr and something we need to land upstream before merging upstream.)
The ljsyscall change is going upstream here: https://github.com/justincormack/ljsyscall/pull/193. …

Numa upstream

---

src/lib/timers/ingress_drop_monitor.lua
src/program/lwaftr/run/run.lua
src/program/snabbnfv/traffic/traffic.lua

WDYT @lukego?  We found it useful to know when the slow part of our system was the NFV and not the guest.  Otherwise you can NACK it, that's fine, we keep it in the lwaftr as it is.
Following up with your comments from https://github.com/snabbco/snabb/pull/1039#issuecomment-254593224:
> Please allow me to zoom out for a moment, not to suggest changing this patch, but rather to map out the context for this whole ingress-drops business mostly for the sake of future directions.
> 
> Here is how I have it all in my head:
> 
> The problem we want to solve is to detect when a Snabb process is overloaded and then to run a callback. The callback could take corrective action (JIT flush) or provide diagnostics (log message).
> 
> Definition: Snabb is overloaded when the average packet arrival rate …

Warn on ingress drop in NFV

---

src/lib/protocol/ipv4.lua

Checksum method in `lib/protocol/ipv4.lua` always recalculates an IPv4 header checksum. The checksum field must be set to zero before recalculation.
There was a checksum unit test function in the module but it couldn't detect this error because the sample packet had its checksum field equals to zero.

Reset IPv4 checksum before recalculating it

---

src/lib/ipsec/aes_128_gcm.lua

We want AUTH_SIZE to be 12 since this is the size of what ends up as the integrity check value.  We can henceforth talk to Linux's IPsec stack (testcases follows in a separate PR)

ipsec: Fix AUTH_SIZE

---

src/lib/protocol/tcp.lua

This PR fixes a typo that made `tcp:new()` error and adds a test case.

Fix typo in lib.protocol.tcp constructor

---

src/core/app.lua

This results in the invariant that each app's push function will be run after packets were pushed on its incoming links.  It might run before as well.

Sort links instead of apps for breathe order.

---

src/core/app.lua

@wingo could you please ACK/NACK this change in a comment before I merge onto next?
Background: The latest link topology change from @wingo brings new semantics: now the pull() method of an app is only called for apps that actually have some input links. This seems reasonable since the purpose of push() is to process packets queued on input links.
This fix simply updates the expectation of how many apps the engine will push() to count only the ones with input links rather than all apps.

engine: Fix selftest() method for link topology change

---

src/apps/test/synth.lua

The `Synth` up would send a multiple of `engine.pull_npackets` if it had more than one `size`, now it sends `pull_npackets + (pull_npackets % #sizes)` per breath.

apps.test.synth: send correct amount of packets per breath.

---

src/lib/README.cltable.md
src/lib/README.ctable.md
src/lib/cltable.lua
src/lib/ctable.lua

From the README:
Ever been annoyed that you can't create a hash table where the keys are
FFI values, like raw IPv4 addresses, but the values are Lua objects?
Well of course you can key a normal Lua table by any Lua value, but the
key is looked up by identity and not by value, which is rarely what you
want.  `foo[lib.protocol.ipv4:pton('1.2.3.4')]` will not be the same as
`foo[lib.protocol.ipv4:pton('1.2.3.4')]`, as the `pton` call produces a
fresh value every time.  What you usually want with FFI-keyed tables is
to be able to look up the entry by value, not by identity.
Well never fear, *cltable* is here.  A cltable is a data type that
associates FFI keys with any old Lua value.  When you look up a key in a
cltable, the key is matched by-value.

Add data type mapping between FFI and Lua values

---

src/core/app.lua
src/core/link.h
src/core/link.lua
src/lib/timers/ingress_drop_monitor.lua
src/program/snabbvmx/lwaftr/setup.lua

This commit sorts the app graph topologically instead of running it to a
fixed point on each breath.  This eliminates quadratic breath time
complexity as a function of graph size.

Topologically sort app graph

---

src/README.md
src/apps/intel/intel_app.lua
src/apps/packet_filter/pcap_filter.lua
src/core/app.lua
src/core/lib.lua

This branch contains several commits in a series.
The net effect is to replace the library function `lib.timer(duration, mode, timefun)` with a pair of simpler counterparts:
- `lib.timeout(seconds)` returns a function that starts returning true after *seconds* have elapsed.
- `lib.throttle(seconds)` returns a function that returns true but never twice in a *seconds* interval.
The idea is that two simple functions are better than one complex one. *Seconds* is always floating-point so you can write `0.25` for 250ms or `1e-9` for 1ns.
This started with commit a233c98 preventing `lib.timer()` from "saving up" timeouts like a token bucket but then it seemed worth taking a step further.
The case against keeping `lib.timer()`:
- Complex interface that requires many words to describe.
- Punts a …

Replace lib.timer() with lib.timeout() and lib.throttle()

---

src/core/main.lua

Reverse the "fork() into worker and supervisor" logic so that the parent process is the worker and the child is the supervisor.
Certain things become easier when the initially spawned process is the one that actually runs Snabb:
- The core.worker module can setup /var/run/snabb/$pid before exec()ing Snabb. It is important that this sets up the Snabb process rather than its supervisor.
- Running `strace snabb ...` will trace the process running Snabb rather than its supervisor.
- Simpler cleanup code because we don't have to handle the complicated case of interpreting SIGCHLD.
I will merge this straight into the multiprocess branch (#1021) because it fixes a major problem where the shared shm `group` folder is accidentally setup for the supervisor rather than the Snabb process. cc @kbara

core.main: Make supervisor child process instead of parent

---

README.md

The project and repo name were changed from `snabbswitch` to `snabb` but the instructions for building and setting up a build environment were not updated. Additionally, it appears that `sudo` must be used to check `--help` the first time because the `snabb` executable wants to touch `/var` on the first run.

Correct instructions for setting up a dev environment

---

src/doc/branches.md

I propose a new branch `snabbco/snabb#luajit` for landing changes to LuaJIT. I volunteer to maintain this -- but would be more than happy for somebody else to do that if they like.
From the branch description:
- Pulls changes from LuaJIT v2.1 upstream.
- Pulls special features & fixes needed by Snabb.
- Resolves conflicts due to upstream rebases of PRs.
Just now I have suggested that the `luajit` branch will feed directly into the `next` branch. This means that I will be doing all the merges myself without a second pair of eyes. If this becomes a problem then the solution would be for somebody else to maintain the `luajit` branch. (However, if you don't like a change that I merge onto `next` you can always PR a correction there before it is released.)
Just somewhat relatedly, I have …

Add 'luajit' branch for maintenance of our LuaJIT v2.1

---

src/core/app.lua
src/core/link.h
src/core/link.lua
src/lib/timers/ingress_drop_monitor.lua
src/program/snabbvmx/lwaftr/setup.lua

This PR refactors (re)configuration so that compute_config_actions
results in an ordered list of actions, O(n) in the size of the change
rather than of the graph, such that apply_config_actions can just mindlessly
apply them.
apply_config_actions is now a mutating procedure which mutates the app
table, the link table, and the current configuration to reflect the
result of applying the config diff in compute_config_actions.
This PR also includes #1066.

Optimize reconfiguration

---

src/lib/hash/siphash.dasl

Before I ended up with this code, I was testing out some other
permutations.  In the end I settled on input data block 0 being the
low 64 bits, 1 being the next 64 bits, and so on.  I adapted the
64-bit load code but not the 32/16/8-bit loads.  This patch fixes that
bug.
Caught by the ctable selftest; added a new test to prevent future
probs.

siphash: Fix load permutation for avx2 u32/u16/u8 loads

---

src/lib/multi_copy.dasl

Fixes #1143.
Explanation: double-words and single-precision floats have the same size (4-bytes). When it comes to moves and bitwise operations the type of data doesn't matter. That makes possible to replace `vpmaskmovd` (works on packed double-words) for `vmaskmovps` (workd on packed single-precision floats).
I made the PR 2 separated commits to check the AVX-only code works in an AVX2 architecture.
I didn't check performance of both versions. If there's no difference maybe is worth to use the AVX version only.

Support AVX-only architectures in multi_copy.dasl

---

src/README.md
src/apps/bridge/mac_table.lua
src/apps/config/action_codec.lua
src/apps/intel_mp/intel_mp.lua
src/apps/lwaftr/ctable_wrapper.lua
src/apps/lwaftr/fragmentv4_hardened.lua
src/apps/lwaftr/fragmentv6_hardened.lua
src/core/lib.lua
src/core/main.lua
src/core/worker.lua
src/lib/README.ctable.md
src/lib/ctable.lua
src/lib/hash/siphash.dasl
src/lib/yang/binary.lua
src/lib/yang/yang.lua
src/program/config/bench/bench.lua
src/program/lwaftr/quickcheck/quickcheck.lua
src/program/lwaftr/tests/propbased/common.lua
src/program/lwaftr/tests/propbased/prop_sameval.lua
src/program/snabbnfv/neutron_sync_agent/neutron_sync_agent.lua
src/program/snabbnfv/neutron_sync_master/neutron_sync_master.lua

This PR changes ctable to randomly seed its SipHash hash functions.  This has two benefits: we prevent some kinds of DOS attacks if the user is able to programmatically make hash collisions, and we fix an accidentally-quadratic behavior if we incrementally populate a ctable from a sequence of entries that were serialized in hash order (https://github.com/Igalia/snabb/issues/654).

Randomly seed hash function used by ctables

---

src/core/lib.lua

Embarrassingly I made a half-change and `lib.randomseed` didn't do what it said it would in the default case!  This patch fixes the error.  It won't change the property-based tests which actually do specify a seed.

Fix case in which lib.randomseed didn't do its job

---

src/README.md
src/core/shm.lua

Controversial idea for discussion: Make the /var/run/snabb/* shm directories world-readable.
This is more convenient for inspection during development and testing, but less convenient if you are running Snabb on a machine with unprivileged users (e.g. they could map the DMA memory to create backdoors.)
What do we think?

core.shm: Make shm objects world-readable

---

src/apps/socket/unix.lua

Avoiding select() for two reasons.
First, the way that we were passing the fdset argument to select() - as a Lua table - is an NYI for the JIT and forces the code to run interpreted.
Second, we don't really need select(), and can instead deal with failure of read() and write().
This is to help resolve the performance issue on #1147.

apps.socket.unix: Rewrote pull/push to avoid select()

---

src/core/main.lua
src/program/snsh/snsh.lua

The main program runner has better error handling than snsh: it prints a full traceback, and even allows for debugging, while snsh just prints out the error message.  Therefore, allow errors to propagate back to main instead of catching them in snsh.  This is especially helpful when the error manifests first inside snabb's code instead of in the script.
Before:
```
core/link.lua:74: attempt to index local 'r' (a nil value)
```
After (without STP):
```
core/link.lua:74: attempt to index local 'r' (a nil value)
stack traceback:
core/main.lua:149: in function '__index'
core/link.lua:74: in function 'empty'
apps/pcap/pcap.lua:49: in function 'method'
core/app.lua:96: in function 'with_restart'
core/app.lua:515: in function 'thunk'
core/histogram.lua:98: in function 'breathe'
core/app.lua:461: …
```

Improve tracebacks for errors in snsh scripts

---

src/program/snabbmark/snabbmark.lua

This is a small fix to a bug in the snabbmark esp micro benchmark that had noticeable negative effect on the results. See the commit message for more details.
I found this while benchmarking the (raw) ESP routines on lugano-1, here are the results with this patch:

snabbmark esp: prevent GC from being invoked by making local vars local

---

.gitignore

It was causing a building problem when linking the snabb binary:
```
LINK snabb
obj/version_lua.o:(.rodata+0x0): multiple definition of luaJIT_BC_core_version' obj/core/version_lua.o:(.rodata+0x0): first defined here /usr/bin/ld: Warning: size of symbolluaJIT_BC_core_version' changed from 123 in obj/core/version_lua.o to 150 in obj/version_lua.o
collect2: error: ld returned 1 exit status
Makefile:60: recipe for target 'snabb' failed
make[1]: *** [snabb] Error 1
make[1]: Leaving directory '/home/dpino/workspace/snabb/src'
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 2
```

Remove src/core/version.lua from .gitignore

---

src/apps/socket/unix.lua
src/core/lib.lua

The test suite output has become very long and repetitive when there are errors, so much so that Github truncates the report ([example](https://gist.github.com/lwaftr-igalia/52ef86d3ab93dd8859d0726a180f486e)). This removes the worst offender, generating hundreds of lines.

Avoid the most repetitive output in tests

---

src/apps/ipfix/README.md
src/apps/ipfix/ipfix.lua
src/program/ipfix/README.md
src/program/ipfix/probe/README
src/program/ipfix/probe/probe.lua
src/program/ipfix/tests/bench.sh

This branch merges in the new ARP app to the IPFIX exporter, so that you don't have to specify MAC addresses when running the VNF.  It also adds some minimal `ipfix probe` documentation.

Integrate ARP into IPFIX exporter

---

src/apps/ipv4/arp.lua
src/program/ipfix/probe/README
src/program/ipfix/probe/probe.lua
src/program/ipfix/tests/collector-test.sh

This PR fixes a few minor issues with `ipfix probe` and also adds an integration test that uses `nfcapd` from the `nfdump` suite to test the app with a real IPFIX collector program. It checks that the collector sees the right number of flows & packets from a short run of the probe & collector on test traffic.
The modifications include:
* change ARP app to not read any incoming packets until the next hop MAC is resolved (to avoid losing template packets that the probe sends)
* allow `tap` devices in `ipfix probe`
BTW: it doesn't matter for this test, but I noticed that if the `ipfix` app gets support for exporting over TCP/SCTP then it may need another input link for incoming responses from the collector.
Also, should the test script be a `selftest.sh` so it's automatically run? Wasn't …

Add an integration test for ipfix probe using an ipfix collector

---

src/apps/ipfix/ipfix.lua
src/program/ipfix/tests/collector-test.sh

This PR fixes a bug in the IPFIX app's netflow v9 mode. It also updates the collector test to be more robust and also test both v9 and v10 modes.
(I meant to include the fix in the previous PR but I overlooked it)

Fixes for IPFIX v9 mode

---

src/lib/pmu.lua
src/lib/pmu_x86.dasl

We want to access the CPU PMU hardware directly instead of via Linux
system calls. This requires the kernel to allow access to the RDPMC
instruction from userspace processes (including Snabb which the kernel
does not know is accessing the PMU.)
This requires the /sys/devices/cpu/rdpmc value to be 2 on newer
kernels (4.0) or 1 on older kernels.
This change makes Snabb attempt to raise the /sys/devices/cpu/rdpmc
value up to the highest value that the kernel supports.

lib.pmu: Enable RDPMC via /sys/devices/cpu/rdpmc

---

lib/ljsyscall/syscall/linux/ioctl.lua
src/apps/tap/README.md
src/apps/tap/tap.lua

Support setting of the MTU on the tap device.  This is a bit tricky,
because the kernel only allows manipulation of the L3 (IP) MTU, while
Snabb considers the tap device to be L2 and includes the L2 header in
the MTU.  Various configuration options are introduces to work around
this issue in a flexible manner.
The app can create an ephemeral tap device or attach to a persistent
device managed outside of the Snabb process.  This was already
possible but this commit makes it clear in the README and also makes
sure that an ephemeral device's status is set to "up".
The interface's operational status is monitored and exposed as a stats
counter.

Tap: support MTU, augment stats

---

src/apps/vlan/README.md
src/apps/vlan/vlan.lua

The performance of the VlanMux app (apps.vlan.vlan) is improved by
- avoiding use of pairs()
- avoiding string composition
- serialisation of loops to avoid branches
The forwarding strategy during de-multiplexing has been changed to
forward all packets from the trunk links and accepting drops on vlan
links which are full (instead of only forwarding as many packets as
the fullest vlan link can accept).
Support for different encapsulation schemes has been added: dot1q,
dot1ad and an explicit ethertype to cover non-standard encapsulations.

apps.vlan: improve performance, configurable encapsulation

---

src/apps/ipv6/README.md
src/apps/ipv6/nd_light.lua

Add two new options
* **remote_mac** for static MAC address of `next_hop`
* **quiet** to reduce verbosity
Add a `reconfig` method, fix a bug in NS processing.

nd_light update

---

src/apps/intel/intel10g.lua
src/apps/intel/intel_app.lua
src/apps/intel_mp/intel_mp.lua
src/apps/intel_mp/testrecv.lua
src/apps/intel_mp/testsend.snabb
src/apps/intel_mp/testup.snabb
src/apps/intel_mp/testvlan.snabb
src/apps/intel_mp/testvmdqtx.snabb
src/lib/hardware/pci.lua
src/lib/io/virtual_ether_mux.lua
src/lib/timers/ingress_drop_monitor.lua
src/lib/virtio/net_device.lua
src/program/ipfix/probe/README
src/program/ipfix/probe/probe.lua
src/program/lisper/dev-env-perftest/baseline.lua
src/program/lisper/dev-env-perftest/count.lua
src/program/lisper/lisper.lua
src/program/lwaftr/loadtest/loadtest.lua
src/program/packetblaster/lwaftr/lwaftr.lua
src/program/snabbmark/snabbmark.lua
src/program/snabbnfv/fuzz/fuzz.lua
src/program/snabbnfv/traffic/traffic.lua
src/program/snabbvmx/lwaftr/lwaftr.lua
src/program/snabbvmx/lwaftr/setup.lua
src/program/wall/common.lua
src/program/wall/filter/README
src/program/wall/spy/README
src/program/wall/tests/bench.sh

This PR is a reworking of #1199 which tries to first adapt network functions to be agnostic as far as whether they are using the old intel10g driver or the new intel_mp driver.  It does this by adding `rx` and `tx` fields to the PCI driver info structure, letting network functions know what link names to use.  It renames the `ndescriptors` property of `intel_mp` to `ring_buffer_size`, and adds a corresponding initarg to the old intel10g driver.  Finally it enables VMDq whereever network functions were setting a MAC address; see #749.
I have a few more unpushed commits to make corresponding changes to the lwAFTR and the changes that @teknico and @takikawa made to the packetblaster / firehose, and the commit that actually changes over the `pci.device_info()` function to prefer `intel_mp`, …

Driver independence

---

src/lib/ctable.lua

This PR should fix issue #1212. I tested it by running `status=0; while [ $status -eq 0 ]; do sudo ./snabb snsh -t lib.ctable; status=$?; done` and waiting for a failure. Without the commit, it fails in about a minute or so of waiting. With the commit, I've left it running for 20+ minutes.
I also tested it by adding an explicit `collectgarbage()` call to trigger the bug immediately.

Adjust ctable selftest to avoid assertion failure

---

src/apps/socket/unix.lua

Hi @lukego, It looks like during the unix socket rewrite to remove `select()` a couple of months ago, the check for `local bytes = S.read()` returning 0 (EOF) was removed, and changed to `if not bytes`, which only catches errors, as ljsyscall converts -1 to a nil return value, and 0 is true.
This means EOF is not caught, so when the socket is terminated from the remote side, the app goes into a loop returning empty allocated packets.
This PR keeps handling for errors (`not bytes`) which includes EAGAIN and re-adds the `bytes == 0` check for EOF - resetting the socket.

Fix Unix socket EOF handling

---

src/apps/intel/README.md

The app is called `Intel82599`, not `Intel10G`.

Correct name of Intel 82599 app in docs

---

src/apps/intel_mp/test_1g_sw_sem.snabb

I think the original intent of this test was to test intel_mp without
any rxq/txq, as in test_10g_sw_sem.snabb.  However in the refactoring of
the default values of rxq/txq and how lib.parse was used to provide
defaults, rxq/txq got turned on, which prevents the test from working as
nic:stop recursively acquires the semaphore.

Attempt to fix apps/intel_mp/test_1g_sw_sem.snabb

---

src/apps/intel_mp/intel_mp.lua
src/apps/intel_mp/loadgen.lua
src/lib/hardware/pci.lua
src/lib/io/virtual_ether_mux.lua
src/program/firehose/firehose.lua
src/program/packetblaster/packetblaster.lua

This PR flips the switch in `lib.hardware.pci.device_info` to prefer the intel_mp driver instead of intel10g.  It also ports over the `firehose` and `packetblaster` programs to intel_mp, also porting the `loadgen` app from intel10g.  All credit to @teknico and @takikawa for the great patches!

Use intel_mp driver instead of intel10g driver

---

lib/ljsyscall/syscall/linux/syscalls.lua

Fixes #1200.
`get_mempolicy` syscall returns an EINVAL if argument maxnode is lower than the value of MAX_NUMNODES defined in the system:
```
int get_mempolicy(int *mode, unsigned long *nodemask,
unsigned long maxnode, void *addr,
unsigned long flags);
```
In ljsyscall `S.get_mempolicy` the argument maxnode is mask.size. What the patch does is to check the value of mask.size is lower than MAX_NUMNODES and in that case set mask.size to MAX_NUMNODES.
That fixes the call to `get_mempolicy` in Ubuntu 17.04. I think to properly know if this fix works, the right thing to do is to run the lwAFTR on such system (I cannot since I lack a 10Gb NIC).

Set mask.size equals to MAX_NUMNODES if lower

---

src/lib/hash/siphash.dasl

When a hash table is re-sized automatically, a new hash function is
generated and cast to a generic function pointer type. However, due to
the semantics of ffi.typeof(), a new ctype ID is allocated each time,
which causes sub-optimal transitions to side-traces in already
compiled traces.  This commit makes sure that all hash function
pointers have the same ctype ID to avoid this problem.

siphash: avoid ctype diversity for hash functions

---

src/lib/protocol/gre.lua

The protocol field for GRE should be an ether type; an implementation receiving a packet containing a Protocol Type which is not an ether type should discard the packet (RFC 2784, 2.4). GRE's inner protocol list (_ulp) should thus be the same as Ethernet's, so that GRE:upper_layer() behaves correctly.

Include IPV4/IPV6 in GRE inner protocol list

---

lib/luajit/src/lib_jit.c
src/core/app.lua

This branch makes the engine ensure that JIT traces never cross between the engine and app callbacks. This is intended both to make JIT trace dumps more readable (don't mix engine and apps in the same trace) and to limit the impact of issues like JIT blacklistings (prevent problems in one app from propagating into other apps or the engine.)
This is achieved using a new primitive function `jit.tracebarrier()` that JIT traces cannot cross. During recording, a call to `jit.tracebarrier()` will immediately finish the current trace and then start a new root trace. This appears as a "trace stitch" in the log.
This branch makes the engine execute such a trace barrier immediately before and after each call to an app.
Performance impact needs to be evaluated. See also raptorjit/raptorjit#115.

engine: Separate JIT traces for each app callback

---

lib/luajit/src/lj_record.c

Record calls to blacklisted functions the same way as calls to
uncompiled functions. This allows for the possibility that a
blacklisted function can be successfully recorded as part of a larger
trace.
This is specifically intended to fix the problem where a tiny utility
function somewhere, such as `ntohs`, is not able to be compiled in
isolation for some reason and that ends up preventing all of its
callers from compiling too.
This has tended to happen for obscure reasons like "the utility
function ends with a tail-call to a C library routine" and with this
patch we should not need to worry about such minutiae anymore. (We
should be able to retire the "wrap in parenthesis to prevent a
tailcall" trick that some people are familiar with.)
More background:
- How the trace recorder treats …

lj_record.c: Record IFUNC/IFUNCV the same as FUNC/FUNCV

---

src/core/memory.c

This logs a message (similar to what appears in `dmesg` if a procces receives a `SIGSEGV`) when snabb encounters a segmentation fault.
It looks like this:
```
$ sudo ./snabb snsh -e 'require("ffi").cast("int*", 1234)[0] = 42'
snabb[3723]: segfault at 0x4d2 ip 0x446f93 sp 0x7ffc6de72da0 code 1 errno 0
Segmentation fault (core dumped)
$ 
```
Interpreting possible `si_code` and `si_errno` usually requires some digging into `/usr/include`.
Cc @lukego

core/memory: log segfault details for unhandled SIGSEGV

---

src/apps/pcap/pcap.lua

`mode` was not passed to `io.open`.

Fix file mode in PcapWriter:new

---

src/core/link.lua

Due to how the engine works, the case that a link is non-empty between
breaths is rare (specifically, it should only occur when an app pushes
to a “slow” output interface). That’s probably why this went unnoticed
until now. I don’t even have a case that triggers this bug, it just came
to me.
Sidenote / only related in spirit: this is somewhat of a foreshadowing of problems that will need to be solved in #1185 (integrated inter-process links) and are sidestepped in #1186 (specialized inter-process links/apps). Specifically, the need to synchronize process-shared link creation and destruction. 
Vita currently uses the specialized inter-process links/apps which depend on one side of the link being explicitly promoted to take care of creating and freeing the link resource. This creates an …

core.link: free any packets left in link when freeing link

---

src/program/top/top.lua

The formulation that was supposed to re-open counters on configuration
changes actually triggered re-opening on every polling.
Cc @alexandergall

top: fix bug where counters were redundantly reopened

---

src/program/lwaftr/run/run.lua

Cherry-pick https://github.com/Igalia/snabb/pull/1005/commits/3e7d2b5e1864959186c393ea65f2e9f3a364a7d3 to fix loadtest.

Fix loadtest

---

src/apps/ipv4/reassemble.lua
src/apps/ipv6/reassemble.lua

Fixes a copy paste error at end of apps.ipv4.reassemble’s selftest.

apps.ipv4.reassemble: fix a copy paste error at end of selftest

---

src/program/lwaftr/tests/propbased/selftest.sh

Sadly, these tests are flaky and its failures are gating merges of
unrelated patches.  We'll work on fixing these tests on Igalia's lwaftr
branch.

Disable lwAFTR property-based tests unless SNABB_ENABLE_FLAKY_TESTS is set

---

lib/luajit/src/lj_auditlog.c
lib/luajit/src/lj_auditlog.h
lib/luajit/src/lj_ctype.c

Add more debug information to the auditlog to support more detailed decoding in Studio (studio/studio#99).
Logging of CTypeID definitions is preliminary and does not cover all interesting types yet.

RaptorJIT: Enhance debug information in auditlog

---

lib/luajit/src/Makefile
lib/luajit/src/lj_asm.c
lib/luajit/src/lj_auditlog.c
lib/luajit/src/lj_debuginfo.h
lib/luajit/src/lj_dwarf.c

This updates the RaptorJIT VM to log more useful debug information for Studio:
- Full DWARF debug information is stored inside the audit.log.
- Fixed machine code to IR code map logging.
- Add names of internal VM functions.
The IR visualization looks like this nowadays (with disassembly on mouseover tooltip :-))

RaptorJIT: Pull more VM debug logging for Studio

---

lib/luajit/src/lj_auditlog.c

Quickly pulling this fix to RaptorJIT `audit.log` logging of IR constants. There was a bug where 64-bit values could be mistaken for points to Lua objects and dereferenced, which could cause a segfault or bus error. This is fixed now.

RaptorJIT: Fix bug in auditlog constant logging (can crash)

---

src/core/app.lua
src/lib/ptree/worker.lua

This PR enables vmprofiling in workers. It fixes the issue of inspecting a worker process with Studio (which didn't work since `audit.log` could not be found).
Performance doesn't suffer with vmprofiling enabled.
```bash
$ SNABB_SHM_ROOT=/tmp/shm SNABB_SHM_KEEP=1 \
./snabb lwaftr run --cpu 11 --name lwaftr --conf lwaftr.conf --v4 82:00.0 --v6 82:00.1
```
```bash
$ sudo ./snabb loadtest find-limit from-inet-0550.pcap "NIC 0" "NIC 1" \
02:00.0 from-b4-0550.pcap "NIC 1" "NIC 0" 02:00.1
Success.
9.999
```
When opening the process with Studio it shows profiling data for every worker app.

Enable vmprofiling in workers

---

src/apps/ipsec/README.md
src/apps/ipsec/esp.lua
src/apps/ipsec/selftest.sh
src/apps/ipsec/test-linux-compat.sh
src/apps/ipsec/test-linux-compat.snabb
src/program/snabbnfv/README.md
src/program/snabbnfv/nfvconfig.lua
src/program/snabbnfv/traffic/README

> This adds a simple ESP 6in6 tunnel app (Tunnel6) to apps.ipsec.esp, and also renames the transport mode app (AES18GCM -> Transport6) to match the naming.
> 
> The apps.ipsec Linux interoperability test is extended to exercise tunnel mode as well.
Why? This is not actually the app used by i.e. Vita. I had originally intended to consolidate the ESP apps in mainline snabb with the ESP apps in Vita, but noticed that this is really not straightforward. It boils down to “how much do you want your ESP app to do?” In the context of Vita the answer is currently “as little as possible”, in other contexts it might be different. I decided to add an ESP tunnel app that is mostly self-contained (you will probably want an `nd_light` in front of it), and serves as a show- and testcase that is …

[ipsec] add tunnel mode esp app

---

src/lib/numa.lua

As per https://github.com/snabbco/snabb/pull/1267#issuecomment-361235782
I still believe this to be expected behavior and possibly the correct fix (I have included an alternative approach that attempts to be... progressive), unless `has_numa` is supposed to behave differently than I expected. Let me explain:
I observe a difference in behavior on a system that has only a single NUMA node, and a system which has no NUMA at all. E.g.
Single NUMA node:
```
$ numactl -H
available: 1 nodes (0)
node 0 cpus: 0 1 2 3 4 5 6 7
node 0 size: 15943 MB
node 0 free: 13209 MB
node distances:
node   0 
0:  10 
$ numactl -m 0 echo hello
hello
```
No NUMA support:
```
$ numactl -H
No NUMA available on this system
$ numactl -m 0 echo hello
numactl: This system does not support NUMA policy
```
On both of those …

lib.numa: selftest fails on non-NUMA systems

---

src/doc/branches.md

@wingo and I volunteered to maintain this branch. Initially it's for making Snabb-on-RaptorJIT work well enough for merge to mainline. In the future we can use it for pulling new RaptorJIT updates too.

doc/branches.md: Add snabbco/raptorjit integration branch

---

lib/ljsyscall/syscall/linux/c.lua

This PR merges in a patch to upstream ljsyscall:
https://github.com/justincormack/ljsyscall/pull/224
The original commit log follows:
Otherwise, passing a negative seek amount as a normal Lua number will
involve a cast from double to uint64.  In C it's undefined behavior when
a double outside the [0,2^64) range is cast to uint64.  In Lua we try to
additionally accomodate the range [-2^63, -1], but there is a bug on
x64-64 and might be a bug on other platforms:
https://github.com/LuaJIT/LuaJIT/pull/415
However it's cheaper to simply target an int64_t when you want to allow
negative numbers, as is our case, because you don't have to do assembly
heroics for it to do what you want.  The `tonumber` call in the return
of `linux.lua:lseek` indicates anyway that our range is not the full
64-bit …

Make "offset" arg to lseek a signed integer

---

Makefile

On PR #1340 the CI makes much more progress on the raptorjit branch, but there's still a failure due to breaking a selftest for glibc <2.7 compatibility (https://gist.github.com/SnabbBot/494e9caf010b44602e2b4124b381441d). This PR fixes that.

Add luajit CFLAGS back into Makefile

---

src/apps/example/asm.dasl
src/lib/hash/siphash.dasl
src/lib/multi_copy.dasl

When Snabb switches to LuaJIT's GC64, FFI allocations might be in the
64-bit range.  This commit adapts the memory references to immediate
addresses to account for 64-bit immediates.

Load potentially 64-bit values using mov64

---

src/core/memory.lua

Unmap temporary hugepage memory mapping that is used to determine the page’s
physical memory address before returning the tagged mapping. This way we avoid
a superflous mapping in the process’ virtual memory space.

core.memory: unmap tmpptr in allocate_huge_page

---

src/lib/pmu.lua
src/lib/pmu_x86.dasl

A machine readable listing of available PMU events for various AMD cpu models was not available, so instead I added a way to specify events by raw code by supplying  a hexadecimal string literal (i.e., "0x00c0").
That way, lib.pmu is still useful on AMD CPUs for brave souls armed with a processor manual. I.e., this will give you the number of missed branches on Ryzen:
```
function foo () local x = 0; for i=1,1e6 do x = x + i; end; return x; end
pmu.profile(foo, {"0x00C3"})
EVENT                                             TOTAL
cycles                                        3,209,354
instructions                                  6,017,991
0x00C3                                              447
```
Cc @lukego

lib.pmu: rudimentary support for AMD family 15h+ CPUs

---

src/lib/README.ctable.md
src/lib/ctable.lua

My motivation for this change is to be able to perform a JIT flush after a table has been resized, which turned out to be crucial for performance in the case of the ipfix app. I also use it to emit an informational message about the growth of the table.

Add optional callback to the CTable:resize() method

---

src/README.md
src/core/app.lua

Add `engine.stop()` as a way to trigger the orderly shutdown of apps via `:stop()` callback. This is a compromise solution to #1276.
If you want your apps to all shutdown in an orderly way with their `stop()` methods called then you can achieve this by calling `engine.stop()`. If your Snabb process terminates abruptly (`kill -9`, segfault, etc) then naturally this call will not be made and the stop methods will not run. (If you *really* need the shutdown actions to run then you can arrange for our separate supervisor process to do that, see #1276.)
Resolves #1276.

Add engine.stop() to stop all apps

---

src/core/app.lua

Just a tiny change to make Studio automatically detect Snabb profiler data in more contexts: name the profiler datasets with the `.vmprofile` filename suffix.

core.engine: Add .vmprofile suffix to filenames to help Studio

---

src/apps/vhost/vhost_user.c

Found via GCC 8.2's -Werror=stringop-truncation.  NUL termination is required by the AF_UNIX socket API.

Ensure vhost-user socket paths are NUL-terminated

---

src/apps/intel_mp/intel_mp.lua

Move the ctype declaration of txdesc_t out of the init_tx_q() method
to make its ctype identical in all instances of the driver.  This
eliminates certain side traces in the transmit code path.

intel_mp: fix ctype diversity for txdesc_t

---

src/core/packet.lua

The pointer type passed to append() and prepend() should always be
canonicalized to "uint8_t *" to avoid side traces in code that uses
these functions.

packet: cast pointer arg in from_pointer()

---

README.md

The old link was reported to have gone stale.

README.md: Update Slack invite link

---

src/apps/intel_avf/README.md
src/apps/intel_avf/intel_avf.lua
src/apps/intel_avf/selftest.sh
src/apps/intel_avf/tests/back2back/test.snabb
src/apps/intel_avf/tests/info/test.snabb
src/apps/intel_avf/tests/setup.sh
src/apps/intel_mp/intel_mp.lua
src/apps/test/README.md
src/apps/test/npackets.lua
src/apps/test/synth.lua
src/lib/hardware/pci.lua
src/lib/hardware/register.lua
src/lib/macaddress.lua

This PR includes @petebristow’s Intel AVF driver in #1411, as well as some minor polish and a bug fix or two. Tested on lugano-1 with both x710 and xl710 cards (rev 01) like so:
```
sudo SNABB_AVF_PF0=0000:03:00.0 apps/intel_avf/selftest.sh
```
(It’s possible to test this with a single unwired port/PF afterall.)
Cc @lukego 
Would be neat to get this into the pending release!

Integrated intel_avf driver

---

src/apps/intel_mp/README.md
src/apps/intel_mp/intel_mp.lua
src/apps/intel_mp/test_10g_2q_loopback.snabb
src/apps/intel_mp/test_10g_loopback.snabb
src/apps/intel_mp/test_10g_vmdq_loopback.snabb
src/apps/intel_mp/test_10g_vmdq_loopback_self.snabb

815ac59 Implements Tx->Rx MAC Loopback mode useful for diagnostics/testing purposes
8879ff0 Enables TX loopback in VMDq mode (git history seems to indicate this was intended to be enabled before, but wasn’t)
cd528a6 is a bit interesting in the way that this bug was never triggered in actual use (I was only able to hit it by trying to run two conflicting instances on the driver on the same port). I don’t dare to remove the `if` statement all together though.

Tx->Rx MAC Loopback mode support and minor fixes for intel_mp 82599

---

src/core/main.lua

Open auditlog during initialization, instead of waiting for engine to start.
Probably we want to open the auditlog even when the engine is never started? Can not hurt to have an auditlog even for non-dataplane processes like e.g. ptree managers? Cc @lukego 
Resolves: https://github.com/snabbco/snabb/issues/1428

core.main: open auditlog during initialization

---

src/apps/intel_mp/intel_mp.lua

Used to be that `rxdrop` only included packets dropped on queue 0 for Intel 82599 based cards. This branch makes it so that `rxdrop` includes all dropped packets.
Caveat: I would extend cb17d43 to do the same for i210/i350 based cards but do not have any to test right now.

Intel_mp: rxdrop counter fixes for 82599

---

src/README.md
src/apps/keyed_ipv6_tunnel/tunnel.lua
src/core/lib.lua

A few changes to `lib.hexundump`:
- accept white space between bytes
- by default, raise an error if less than *n* bytes could be parsed
- add extra parameter to either supply an error message or force the old behaviour
Rationales:
- accepting white space makes `hexundump` symmetric with `lib.hexdump`
- new default behaviour of raising as error less that *n* bytes takes burden to check corner cases off the caller

Picky hexundump

---

src/README.md
src/apps/intel/intel10g.lua
src/apps/intel_mp/intel_mp.lua
src/lib/hardware/README.md
src/lib/hardware/pci.lua

Make sure PCI devices are unbound before attempting to map their memory in intel_mp. This a second take on #1296:
> Since Linux 4.5, devices that are bound to a kernel driver can't have
their memory mapped by userspace under the default configuration of
CONFIG_IO_STRICT_DEVMEM=y.
Why do I think we avoid races this time?  Basically what we have during device initialization is a state machine `FREE -> INIT -> SHARED`.  Master will acquire the exclusive lock, unbind the device, enable bus mastering, and then map device memory and do the init before allowing the lock to be shared (`INIT` state). Other processes will wait for the shared lock and map device memory only after master has finished unbinding and initialization (`SHARED` state).
During looking at this I also stumbled upon the fact …

Unbind PCI devices before mapping their memory (take two)

---

src/core/app.lua

The goal of this change is to simplify the loop structure of the Snabb engine to make it more likely that the compiler can find and optimize the packet-processing loops. In particular, it can help in the situation when the program starts in an idle state with no packets to process. In that case, we want to avoid that traces compiled for this initial workload have a negative impact on the creation of traces for the actual (non-idle) workload.
See https://github.com/snabbco/snabb/issues/1414 for an analysis with a simplified engine.
I would like to encourage people to try this out with their own Snabb programs and provide feedback.

core.app: use implict pull/push loops in breathe()

---

src/dasm_x86.lua
src/doc/genbook.sh
src/lib/README.poptrie.md
src/lib/poptrie.lua
src/lib/poptrie_lookup.dasl

This branch contains the beginning of an implementation of [Poptrie](http://conferences.sigcomm.org/sigcomm/2015/pdf/papers/p57.pdf). So far it can...
- build the poptrie lookup structure for prefixes of up to 64 bits
- look up keys in the poptrie fairly quick using a DynASM based lookup routine
- be instantiated using a pre-built poptrie structure
Performance on an Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz (Haswell, Turbo off)
```
PMU analysis (numentries=10000, keysize=32)
build: 0.1290 seconds
lookup: 13217.09 cycles/lookup 28014.35 instructions/lookup
lookup64: 122.94 cycles/lookup 133.22 instructions/lookup
build(direct_pointing): 0.1056 seconds
lookup(direct_pointing): 5519.01 cycles/lookup 11412.01 instructions/lookup
lookup64(direct_pointing): 89.82 cycles/lookup 70.72 …
```

A little generic poptrie implementation

---

src/core/main.lua
src/core/packet.lua
src/lib/interlink.lua

In multi-process Snabb DMA huge pages are only released to the operating system
once the group’s parent shuts down. This commit makes it so that packets
allocated by workers are released into the group freelist when a worker shuts
down. This addresses two issues:
- workers can have packets allocated by other workers on their freelist at the
time of their shut down
- DMA huge pages used for packets owned by workers that have shut down would
otherwise leak (i.e. not be available to the OS and other processes until
the group parent shuts down)
4da22e6  intends to handle both issues by recycling all allocated packets
within the process group (to match the DMA huge page management model.)
58fa77f is a minor, barely related fix.
Cc @lukego

core.packet: release packets to group freelist on shutdown

---

src/core/app.lua
src/core/main.lua
src/core/packet.lua
src/lib/ptree/worker.lua
src/lib/scheduling.lua
src/program/lwaftr/migrate_configuration/migrate_configuration.lua
src/program/lwaftr/tests/config-migrations/selftest.sh
src/program/snabbnfv/traffic/traffic.lua

This fixes a performance regression caught while running the benchmark matrix for the Octarina release. See 247ef95 and 5f045e7.
Also includes a fix for a test regression of lwAFTR, see 992a845.

Fixes for regressions in max-next headed for Octarina release

---

src/apps/intel_avf/intel_avf.lua

Updates the AVF driver to use the new PCI resource acquisition API from
#1436
Fixes the currently broken :new() routine. The breakage happened when the avf
branch was integrated with next, and I failed to test the merge. ^^'
7722f0d Frees PCI resources and remaining packets on rx/tx queues on shutdown. This
fixes a resource leak. Somehow I overlooked this omission completely during the initial integration. :-)

intel_avf: fix integration breakage and free resources on shutdown (stop())

---

src/lib/yang/data.lua
src/lib/yang/path_data.lua
src/program/config/common.lua

This fixes a few oversights regarding the handling and validation of choice bodies. 
e96ae1a in particular could use a set of eyes familiar with lib.yang. Was there a purpose for the `order` parameter that I am not seeing?
Cc @wingo @dpino @xray7224

Various YANG fixes related to choice statements and the consistency checker

---

src/lib/numa.lua

This addresses an issue in environments where `'/sys/devices/system/cpu/cpu'..cpu..'/cpufreq/scaling_governor'` is not present. One example of such an environment are EC2 instances on the AWS cloud.
After this patch, instead of crashing, `lib.numa` will print a warning that the CPU governor could not be verified.

lib.numa: gracefully handle failure to read CPU performance governor

---

src/lib/ptree/ptree.lua

Addresses orphaned counter/gauge aggregates accumulated by lib.ptree. Adds a check whether an aggregate is still backed by any active counter source; if not (i.e., it is orphaned) delete the respective aggregates.
Before this patch, apps with unique names that were started and stopped over the lifetime of the Snabb program using lib.ptree would cause the leader to accumulate past counter aggregates, leading to stale links shown in `snabb top`, and eventually using up all space in `/var/run/snabb`.

lib.ptree: cleanup obsolete aggregated stats

---

src/arch/checksum.dasl

This fixes a bug in our scalar x86 IP checksum implementation, where some
carries where missed. Really hard to find with random testing, added a
systematic test case for carry propagation.

arch/checksum: fix bug in carry propagation

---

src/apps/intel_avf/README.md
src/apps/intel_avf/intel_avf.lua
src/apps/intel_avf/tests/back2back/multicast.snabb
src/apps/intel_avf/tests/back2back/rss.snabb
src/apps/intel_avf/tests/back2back/test.snabb
src/apps/intel_avf/tests/back2back/vlan.snabb
src/apps/test/README.md
src/apps/test/synth.lua
src/lib/hardware/pci.lua
src/program/top/top.lua

This extends the Intel AVF driver to support multiple RSS queues via an IO app to attach to each individual queue (just like our Connect-X driver).
This also adds support for VLAN tagging/untagging in the driver, fixes a perf issue, canonicalizes the SHM counter location of the driver, and includes a fix to make `snabb top` correctly handle interfaces that do not specify a link speed (as typical with AVF devices).
Depends on: https://github.com/snabbco/snabb/pull/1451

Updated Intel AVF driver with VLAN+RSS support

---

lib/luajit/src/lj_trace.c
src/core/app.lua
src/lib/timers/ingress_drop_monitor.lua

This includes some improvements to ingress_drop_monitor as well as an experimental patch[1]  for RaptorJIT that prevents “long-tail trace” generation.
- [1] https://github.com/raptorjit/raptorjit/pull/260
I’ve decided to include this since it has worked well for lwAFTR and I think is ready for broader application in Snabb upstream.

Tracing JIT stability improvements from lwAFTR

---

src/apps/interlink/freelist_instrument.lua
src/apps/interlink/test_sink.lua
src/apps/interlink/test_source.lua
src/apps/interlink/wait_test.snabb
src/core/app.lua
src/core/group_freelist.lua
src/core/packet.lua

This adresses
- #1468
by employing a smarter data structure for the group freelist (MPMC bounded queue).
It also moves the rebalancing house keeping into `packet.free`, and keeps limits on the upper bound of work performed in any rebalance/reclaim step.
In the density plots below we have `master` in red and this branch in blue (green was an alternative wip branch).
This certainly improves latency and thus performance of interlinks, however this does not make interlinks scale without restriction. The benchmarking I did seems to show that sharing memory between cores still turns into a bottleneck, and depending on your CPU architecture you are going to run into that sooner or later. I did compare results between Intel and EPYC machines and they are quite different. But for here and now I’m …

Use MPMC bounded queue for group freelist

---

src/apps/mellanox/connectx.lua
src/apps/mellanox/connectx_test.lua
src/lib/numa.lua
src/program/lwaftr/setup.lua

- cf73e1e01c401d1cfdd96454dc1be7450a0b7cd6
- 3d8ddccc07cd0164d3e365163d4fb928424f85e6
Depends on #1473

Fixes for lwAFTR in many-worker configurations

---

src/apps/lwaftr/binding_table.lua
src/apps/lwaftr/lwaftr.lua
src/lib/ctable.lua
src/lib/hash/siphash.dasl

Running CI for the Alpina release showed a performance regression in the lwaftr benchmark.
I’ve triaged this to not be due a specific code change, but an existing condition where the previous code generated traces that unnecessarily invoked the GC.
These two commits eliminate some casts that could set off the GC and some side traces to make perf more predictable:
- 5fe89b5ba7ad977ceb338294cb6f87e1f819aa15 don’t flush lookups early, always flush them at the end of `push` (I had increased the queue size for this, but it should be fine with the default `engine.pull_npackets` and there is a new assertion to check the currently hardcoded queue size is sufficient.)
- 4706127a25f175aa90b6be6f4571a2786a7ec1fd optimized the best-case code for siphash’s `make_multi_hash` method to not generate side …

Fix lwAFTR trace performance issues (for release Alpina)

---

src/apps/mellanox/connectx.lua
src/apps/mellanox/connectx_test.lua

This fixes a bug where per-queue rxdrop counters were not counted.

apps.mellanox: use default enable_counters setting

---

src/apps/interlink/receiver.lua
src/apps/interlink/transmitter.lua
src/core/group_freelist.lua
src/core/packet.lua
src/core/shm.lua
src/lib/interlink.lua
src/lib/scheduling.lua

This set of changes allows to adjust interlink queue, freelist, and group freelist sizes at runtime.
This is useful because some applications might choose larger interlink queue sizes (just like an application might select larger NIC driver receive queue buffers) to allow for longer breath latencies before packets are dropped.

Configurable interlink queue, freelist, and group freelist sizes

---

src/lib/ptree/support/snabb-snabbflow-v1.lua
src/lib/yang/snabb-snabbflow-v1.yang
src/program/ipfix/lib.lua
src/program/ipfix/probe/probe.lua
src/program/ipfix/tests/test.lua
src/program/ipfix/tests/test_v4_v6.conf

[ipfix probe: cleanup code, optimize operation without software rss](https://github.com/snabbco/snabb/commit/5923add8e3800d3730032b8463dbd3f5b9279119) 
This reorganizes the program.ipfix.lib module and optimizes the case
of a single embedded export instance and no flow director classes.
In this case, we do not create the software rss app and simply Join
the inputs to be then processed directly by the ipfix app.
NB: the ipfix app has to take care of extracting packet metadata.

ipfix probe: cleanup code, optimize operation without software rss

---

src/core/group_freelist.lua
src/core/sync.dasl

[core.group_freelist: fix a deadlock](https://github.com/snabbco/snabb/commit/45d3ac768bcb3d394b986062a3a474715f2eb817) 
chunk.sequence was not reloaded on further iterations of the loop.
Use sync.load() to explicitly reload lock-free states.
Panic if we fail to progress after 1000 iterations.

core.group_freelist: fix a deadlock

---

src/lib/poptrie.lua
src/lib/poptrie_lookup.dasl

We used to shift in bits from right to left, thinking that since we are on little endian the addresses are strictly in reverse order. That is not the case! The bytes are swapped but the bits are not! :-)
In the x86 assembly routines we now do `bswap` and then shift down bits from right to left.

lib.poptrie: fix bug where address bits where interpreted in reverse order

---

src/apps/rss/metadata.lua

The original code had the effect of setting the ULP to 255 in this case, which is wrong.  We simply need to treat 59 like any other ULP.

apps.rss: remove 59 (no-next-header) from list of IPv6 extension headers

---

src/lib/yang/list.lua

Prior attempt to move up child node to parent was broken. (hash parameters no longer match)
Not even sure if what was attempted is possible as we do not know the children's keys at this point?
Fix by only moving leaf children.

lib.yang.list: fix bug in remove_obsolete_nodes

---

src/apps/ipfix/ipfix-information-elements-local.inc
src/apps/ipfix/ipfix.lua
src/apps/ipfix/maps.lua
src/apps/ipfix/template.lua
src/apps/ipfix/tls.lua
src/apps/ipv4/reassemble.lua
src/apps/rss/README.md
src/apps/rss/metadata.lua
src/apps/rss/rss.lua
src/lib/yang/snabb-snabbflow-v1.yang
src/program/ipfix/probe/probe.lua

- https://github.com/snabbco/snabb/pull/1500
- https://github.com/snabbco/snabb/pull/1501
- https://github.com/snabbco/snabb/pull/1502
- https://github.com/snabbco/snabb/pull/1503
- https://github.com/snabbco/snabb/pull/1504
- https://github.com/snabbco/snabb/pull/1506

Collected changes for June 2023 release: Davion

---

src/apps/ipv4/reassemble.lua

lib.ipv4.reassemble: fix missing argument in call to reassembly_error
Add some unit test cases that exercise error paths.

lib.ipv4.reassemble: fix missing argument in call to reassembly_error

---

src/apps/ipfix/ipfix.lua
src/apps/ipfix/maps.lua

If mk_map() is called via ipfix:reconfig() because the name of a map file has changed, the map ctable will still not be re-created due to its presence in the cache used by mk_map(). This commit uses the ctime of the file to detect whether the ctable needs to be re-created.
ipfix:reconfig() is also enhanced to only re-create the mapping tables if the rest of a template's configuration is unchanged.

apps.ipfix.maps: re-create map ctable if source file has changed

---

src/apps/ipfix/ipfix-information-elements-local.inc
src/apps/ipfix/template.lua
src/apps/ipfix/tls.lua

Due to lack of a standard information element, this template re-uses a private element under the PEN of Progress/Flowmon (39499) to be compatible with their commercial Netflow collector.
The templates parse the TLS handshake record of the client and look for the SNI extension in the Client Hello message for TLS 1.2 and later.

ipfix: add HTTPS templates to extract the TLS SNI

---

src/core/app.lua
src/lib/ptree/ptree.lua
src/lib/scheduling.lua

This was never really used, and probably always or at least for a long time broken, but I found it useful during some testing. This fixes a bug in the mode and adds support for it in `lib.scheduling`.
Also adds supports for configuring per-worker (lib.)scheduling options in ptree.

Fix engine.Hz mode

---

src/apps/mellanox/connectx.lua

The ethernet port speed is read from the eth_proto_oper field of the PTYS register. This field was extended with the ext_proto_oper field in newer devices. In particular, 200G and 400G speeds are contained in this field rather than eth_ptoto_oper.
Which of these fields is valid for the device is determined by the field ptys_extended_ethernet provided by the PCAM (Ports CApabilities Mask) register. Whether this register exists or not is, in turn, determined by the pcam_reg flag of the HCA general cpabilities.

apps.mellanox.connectx: add support for PCAM register

---

src/core/app.lua
src/lib/ptree/ptree.lua
src/lib/scheduling.lua

Depends on: #1509 
Measure time between *now* and last time a packet was freed during a breath, only sleep in `pace_breathing` when we have been idle for at least 1us.
This is intended to make us more conservative with sleeping when handling bursty real-world traffic.

Timed pace breathing

---

src/lib/hardware/pci.lua

This obvious bug prevents the supervisor process from disabling PCI bus mastering.

lib.hardware.pci: fix pcall in shutdown()

---

src/apps/mellanox/connectx.lua

Ignore 0 and negative values in alloc_pages(). This assumes that the function is called with the result of query_pages() for which these values are legal (a negative value indicates that pages can be recalimed by the driver).  In some versions of the firmware on ConnectX7, query_pages() for "regular" pages during initialization returns a negative value that would trigger the assertion.
Allocation of "regular" pages is not part of the card initialization according to the PRM, i.e. this particular problem could also be avoided by removing that call. However, this commit seems more robust.
Note that page reclaims are already handled by the event queue through reclaim notifications.

apps.mellanox.connectx: alloc_pages(): remove assertion
