snabbco/snabb

- src/apps/intel/intel10g.lua
- src/apps/intel/intel_app.lua
- src/lib/hardware/pci.c
- src/lib/hardware/pci.h
- src/lib/hardware/pci.lua
Merge Javier's fine work on more robust initialization and shutdown of the Intel10G app: #360.
> Merge: Intel10G: better initialization / closing

- src/README.md
- src/README.md.src
- src/lib/protocol/README.md
- src/lib/protocol/README.md.src
Includes a tiny general fixup.
> Update API documentation for straightline

- src/apps/intel/intel_app.lua
- src/apps/ipv6/nd_light.lua
- src/apps/ipv6/ns_responder.lua
- src/core/app.lua
- src/lib/nfv/selftest.sh
Small things I have found along the efforts of the last month. I would like someone to sanity check c1c0e08 (Unbind PCI device before using it in intel_app), I feel it might be too naive.
> General bug fixes

- src/apps/bridge/base.lua
- src/apps/bridge/flooding.lua
- src/apps/bridge/learning.lua
- src/apps/ipv6/ns_responder.lua
Also implement the convention that apps should not return a table.
> Adapt bridge and ns_responder apps to straightline semantics

- src/program/snabbnfv/selftest.sh
- src/scripts/cperf/benchmarks/iperf-1500
> [snabbnfv selftest bench] Add default MTU=1500 iperf bench.

- src/program/snabbnfv/traffic/traffic.lua
The optional arguments (only -B) were treated as positional arguments.
> snabbnfv traffic: Fix command-line argument parsing

- src/apps/ipv6/README.md
- src/apps/ipv6/README.md.src
- src/apps/ipv6/nd_light.lua
- src/apps/packet_filter/conntrack.lua
- src/apps/vhost/vhost_user.lua
- src/program/snabbmark/snabbmark.lua
- src/program/snabbnfv/README.md
- src/program/snabbnfv/README.md.src
- src/program/snabbnfv/neutron2snabb/neutron2snabb.lua
- src/program/snabbnfv/nfvconfig.lua
- src/program/snabbnfv/traffic/traffic.lua
This branch contains merges of open PRs:
* #419 `packet_filter.conntrack: Allow non-IP packet arguments`
* #421 `nd_light: Default to unlimited NS retransmissions"`
* #422 `[nfvconfig] Remove obsolete notion of "zerocopy pairs"`
* #423 `neutron2snabb: get profile:bindings from vif_details`
> Integrated merge from PRs to master

- src/apps/packet_filter/conntrack.lua
Previously it was an error to pass non-IP packets to check(). Now
these are treated as not belonging to any session.
Added a brief API summary in comments.
> packet_filter.conntrack: Allow non-IP packet arguments [DRAFT]

- src/apps/ipv6/README.md
- src/apps/ipv6/README.md.src
- src/apps/ipv6/nd_light.lua
Make `nd_light` app default to unlimited NS retransmissions.
> [nd_light] Default to unlimited NS retransmissions

- src/apps/ipv6/nd_light.lua
- src/lib/protocol/datagram.lua
Use static arrays to cache pointers to cdata objects in the nd_light
app and the datagram class.
> Performance enhancements

- src/apps/solarflare/README.md
- src/apps/solarflare/README.md.src
- src/lib/protocol/README.md
- src/lib/protocol/README.md.src
> Documentation fixes amendments

- src/apps/packet_filter/conntrack.lua
- src/apps/packet_filter/pcap_filter.lua
just rebased from the `Integrate_pflua_filter` branch.
> packet_filter conntrack

- src/Makefile
This is for Andy's fix to Igalia/pflua#178.
> Upgrade pflua for a bug fix

- README.md
This branch aims to improve the new user landing experience by explaining more clearly what the project is and how to get started as a user or a developer.
> README and documentation improvements

- README.md
Previously referenced Max's work-in-progress branch by URL.
> README: Update Getting Started link to be in-tree

- src/program/snabbnfv/neutron2snabb/neutron2snabb.lua
- src/program/snabbnfv/neutron2snabb/neutron2snabb_schema.lua
- src/program/snabbnfv/neutron_sync_master/neutron_sync_master.sh
Merge PR #499 to fix CI test failure.
> Fix neutron2snabb selftest

- src/core/app.lua
- src/program/packetblaster/packetblaster.lua
- src/program/snabbnfv/traffic/traffic.lua
> App report fixes

- src/core/counter.lua
- src/program/top/top.lua
Fixes a couple bugs that prevented `snabb top` from working.
> Snabb top fix for next

- .gitignore
- Makefile
- src/Makefile
- src/core/main.lua
Collected fixes to our Makefiles.
> Makefile love

- src/lib/protocol/ipv6.lua
> ipv6:pton: Fix error on invalid address

- src/core/main.lua
* Function programname didn't replace '-' for '_'
* Restricted regular expression that get rids of version numbers in
program and module names.
* Added selftest.
> Allow hyphens in program name

- src/doc/testing.md
- src/scripts/snabb_bot.sh
This patch is already in effect in form of SnabbBot on davos. Also includes some documentation additions.
> Make SnabbBot merge PR branch with “master”

- src/program/firehose/firehose.lua
As discussed on the Mailing-List I did this small fix to make Firehose program work. Thanks.
> Fix to adapt to the latest NIC driver changes

- src/apps/solarflare/selftest.sh
- src/apps/tap/selftest.sh
- src/bench/basic1-100e6
- src/bench/packetblaster-64
- src/bench/packetblaster-synth-64
- src/bench/snabbnfv-iperf-1500
- src/bench/snabbnfv-iperf-jumbo
- src/bench/snabbnfv-loadgen-dpdk
- src/doc/branches.md
- src/doc/genbook.sh
- src/lib/watchdog/selftest.sh
- src/program/packetblaster/selftest.sh
- src/program/snabbnfv/neutron2snabb/selftest.sh
- src/program/snabbnfv/neutron_sync_agent/neutron_sync_agent.sh
- src/program/snabbnfv/neutron_sync_master/neutron_sync_master.sh
- src/program/snabbnfv/packetblaster_bench.sh
- src/program/snabbnfv/selftest.sh
- src/scripts/bench.sh
- src/scripts/process-markdown
- src/scripts/sysv/init.d/snabb-nfv-sync-agent
- src/scripts/sysv/init.d/snabb-nfv-sync-master
- src/scripts/sysv/init.d/snabb-nfv-traffic
- src/selftest.sh
Cc @eugeneia.  Originally https://github.com/eugeneia/snabbswitch/pull/12.
> Merge `wingo-next` to `max-next`

- src/scripts/snabb_doc.sh
This fixes SnabbDoc for #855. This is the version that is currently deployed.
Cc @lukego
> Merge SnabbDoc fix for #855 into next

- CONTRIBUTING.md
Adds a `CONTRIBUTING.md` file as discussed in #761. What did I miss, what should I edit out?
Cc @lukego @kbara @wingo
> Add minimal CONTRIBUTING.md

- src/core/packet.lua
This will be used by the lwAFTR.
> Add packet.shiftright

- src/doc/branches.md
Based according to https://github.com/SnabbCo/snabbswitch/pull/835
cc @lukego
> Add nix maintainer branch

- .gitignore
> Add /lib/luajit/usr to .gitignore

- src/README.md
- src/apps/intel/intel_app.lua
- src/apps/ipsec/esp.lua
- src/apps/ipv6/nd_light.lua
- src/apps/keyed_ipv6_tunnel/tunnel.lua
- src/apps/packet_filter/pcap_filter.lua
- src/apps/rate_limiter/rate_limiter.lua
- src/apps/socket/raw.lua
- src/apps/tap/tap.lua
- src/apps/vhost/vhost_user.lua
- src/core/app.lua
- src/core/counter.lua
- src/core/histogram.lua
- src/core/link.lua
- src/core/main.lua
- src/core/shm.lua
- src/lib/virtio/net_device.lua
- src/program/top/README
- src/program/top/top.lua
Reverts statistics for vhost_user app to avoid the performance regression introduced by it.
See https://hydra.snabb.co/build/178439/download/2/report.html
Depends on #982
> Revert vhost_user statistics

- src/lib/ipsec/README.md
- src/lib/ipsec/aes_128_gcm.lua
- src/lib/ipsec/esp.lua
This implements and adds tests for RFC4303 Appendix A3, re-synchronization of the anti-replay mechanism in the event of massive packet loss.
> Handling Loss of Synchronization due to Significant Packet Loss (RFC4303 Appendix A3)

- src/doc/performance-tuning.md
This PR merges the lwAFTR performance documentation into the main performance-tuning.md document, preferring the wording from the lwAFTR doc.  Thoughts?
> Update perf docs

- src/program/snabbnfv/traffic/traffic.lua
[Note: this PR originally contained two unrelated changes and was edited to contain just one.  What follows is the original PR note.  See https://github.com/snabbco/snabb/pull/1039#issuecomment-254790578 for the update.]
Two changes in this PR from downstream `lwaftr` branch: one to add the "warning" ingress drop monitor to the NFV.  This will simply detect drops and print out a warning to the console when many drops are detected.  The second avoids calling `reconfigure` when the configuration hasn't actually changed.  The former helps us track down which part of a system is slow, and the latter is a minor perf improvement. I'll push to my `optimize` branch to see what hydra thinks.
> Avoid NFV reconfigure when nothing has changed

- src/lib/protocol/tcp.lua
A small lib.protocol.tcp fix from Asumu.
> Merge wingo-next to next

- src/apps/tap/tap.lua
- src/lib/protocol/README.md
Just some things I noticed in my journey to talk IPsec with Linux
> Minor fixes

- README.md
Hello! The mailing list is abandoned.
We should remove it, maybe with mention of slack channel
> Mailing list is abandoned

- src/lib/virtio/net_device.lua
Tables of callback functions are now cached as instance variables rather than being created with `{...}` on every call. These allocations were not being sunk and so this eliminates heap allocation & GC.
This was found easily with VMProfile #1125.
> net_device: Eliminate fast-path table allocations

- src/apps/vhost/README.md
> apps: vhost: README.md: fix typo

- src/Makefile
- src/lib/lpm/README.md
- src/lib/lpm/build_fixtures.pl
- src/lib/lpm/ip4.lua
- src/lib/lpm/ip6.lua
- src/lib/lpm/lpm.lua
- src/lib/lpm/lpm4.lua
- src/lib/lpm/lpm4_248.c
- src/lib/lpm/lpm4_248.lua
- src/lib/lpm/lpm4_dxr.c
- src/lib/lpm/lpm4_dxr.lua
- src/lib/lpm/lpm4_poptrie.lua
- src/lib/lpm/lpm4_trie.lua
- src/lib/lpm/random.dasl
@plajjan something for you to look at if nothing else ;)
> LPM library for IPv4 addresses

- src/lib/ipc/shmem/iftable_mib.lua
Bug fixes and enhancements of `lib.ipc.shmem.iftable_mib`. The `l2vpn` program is still the only user of this code and it should eventually be re-written to use the standard `core.shm` API.
> Iftable_mib update

- src/program/snabbnfv/traffic/traffic.lua
Fix borked code introduced in 3f5d3efbb84a9033b8b7f1021ef47570f4ecce9c.
> Fix adaptation of "snabb snabbnfv traffic" to be driver-agnostic

- src/lib/hash/siphash.dasl
- src/lib/protocol/gre.lua
This integration branch is collecting changes that I have merged but want to test a bit before landing on next.
> Batched merges for next

- src/apps/intel_mp/intel_mp.lua
Initialisation of the shm frame needs to be done in the constructor
method to avoid being overwritten by the frame created in core.app.
Add a copy of the mtu to the device-specific stats table, add a
counter to record the speed of the interface.
> intel_mp: move shm initialization to constructor

- src/apps/intel_mp/intel_mp.lua
- src/lib/hardware/register.lua
Just the minimal changes required to get the I350 driver working on a PowerEdge R720 w/ Dell's . hybrid 2x I350 and 2x 82599ES module.
> [wip] [sketch] Naive i350 fixes

- src/apps/tap/tap.lua
> Bump tap selftest timeout to 0.05 seconds

- src/apps/pcap/README.md
- src/apps/pcap/tap.lua
> Add pcap packet tap

- src/lib/yang/data.lua
- src/lib/yang/schema.lua
This fixes a couple of issues around the parsing and validation of length restrictions, and adds tests for both passing and failing lengths.
> Fix length property testing

- src/apps/vlan/vlan.lua
Leverage packet.shift{left,right} to minimize the amount of data that
needs to be copied when inserting/removing a tag from an Ethernet
header.  In the ideal case, only the src/dst MAC addresses need to
actually be moved.
> VlanMux: optimize tag pop/push

- src/lib/ctable.lua
mmap() silently rounds up the size of the memory region to a multiple
of the huge page size.  This causes munmap() to fail if called with
the original value.
> lib.ctable: fix hugepages allocation size

- src/apps/ipfix/ipfix.events
- src/apps/ipfix/ipfix.lua
- src/apps/rss/rss.events
- src/apps/rss/rss.lua
Add some useful timeline events for Snabbflow
> apps.rss, apps.ipfix: add timeline events

- lib/luajit/src/Makefile
- lib/luajit/src/Makefile.dep
- lib/luajit/src/lib_aux.c
- lib/luajit/src/lj_alloc.c
- lib/luajit/src/lj_alloc.h
- lib/luajit/src/lj_state.c
- lib/luajit/src/lj_state.h
Pulls in https://github.com/raptorjit/raptorjit/pull/268 which we have identified as responsible for our recent performance regression.
> Revert raptorjit to use bundled dlmalloc again
